### ISSUE TITLE
Need help to test NEW AMD feature

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#1017]
Dear community I need you to test a new feature on you AMD GPUs.

Please test #1016 and report the following points:
- Hardware used (GPUs)
- Baseline test: hash rate with the current dev or last release (please run `xmr-stak -V`)
- hash rate with the pull request #1016 
  - once with the some settings than the baseline 
  - once with increased increased intensity (please increase the intensity step wise by 8 until you get an out of memory. Do not increase the intensity to more than 1024 for non VEGA devices )
- post the file `amd.txt`

Direct download [https://github.com/psychocrypt/xmr-stak/archive/topic-useAMDPersistentMemory.zip](https://github.com/psychocrypt/xmr-stak/archive/topic-useAMDPersistentMemory.zip)

I need some test results for older GPUs like HD78XX or HD79XX and the new VegaXX.

CC-ing: @JerichoJones

**Comment by totallyG82** [comment]
I will try this when I get back home in some days. I got both Vega 64 and 7850 2GB

**Comment by hchan123** [comment]
I have two AMD GPUs.  I am just adjusting my Vega 64, my other is an old r5
200.  Did not continue until out of memory since the vega basically stopped
reporting hash rates after bumping both threads to  "intensity" : 1956,

Base:
Version: xmr-stak 2.2.0 a8e83eec

Vega Base:
  // gpu: gfx901 memory:3920
  // compute units: 64
{ "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },
    { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },

HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  102.2 |  101.9 |   (na) |  1 |  998.6 |  996.8 |   (na) |
|  2 |  996.8 |  998.4 |   (na) |
Totals (AMD):  2097.5 2097.2    0.0 H/s

Version: xmr-stak 2.2.0 0a142471
hash rate with the pull request #1016
<https://github.com/fireice-uk/xmr-stak/pull/1016>

   - once with the some settings than the baseline

Vega Base:
  // gpu: gfx901 memory:3920
  // compute units: 64
{ "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },
    { "index" : 1, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },

HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  105.4 |  104.1 |   (na) |  1 |  985.0 |  983.1 |   (na) |
|  2 |  982.3 |  978.9 |   (na) |
Totals (AMD):  2072.7 2066.1    0.0 H/s

  // gpu: gfx901 memory:3920
  // compute units: 64
{ "index" : 1, "intensity" : 1940, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },
    { "index" : 1, "intensity" : 1940, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },

HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  105.0 |  106.3 |   (na) |  1 |  558.4 |  559.6 |   (na) |
|  2 |  558.5 |  558.5 |   (na) |
Totals (AMD):  1221.9 1224.3    0.0 H/s

  // gpu: gfx901 memory:3920
  // compute units: 64
{ "index" : 1, "intensity" : 1948, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },
    { "index" : 1, "intensity" : 1948, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },

HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  105.8 |  106.2 |   (na) |  1 |  248.5 |  296.6 |   (na) |
|  2 |  232.5 |  230.7 |   (na) |
Totals (AMD):   586.9  633.4    0.0 H/s
-----------------------------------------------------------------
Totals (ALL):   1068.1 1123.5    0.0 H/s


  // gpu: gfx901 memory:3920
  // compute units: 64
{ "index" : 1, "intensity" : 1956, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },
    { "index" : 1, "intensity" : 1956, "worksize" : 8, "affine_to_cpu" : 0,
"strided_index" : true },

HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  104.9 |  105.1 |   (na) |  1 |   (na) |  142.0 |   (na) |
|  2 |   (na) |   (na) |   (na) |
Totals (AMD):   104.9  247.1    0.0 H/s

**Comment by netxecute** [comment]
I tried this today.  It ran ok with 1932 intensity.  Crashed immediately at 1940.
Reduced hash rates at 1932..  

PR1016
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  951.8 |  950.8 |  951.4 |  1 |  948.1 |  950.2 |  951.4 |
|  2 |  922.0 |  919.9 |  921.5 |  3 |  918.8 |  919.3 |  921.4 |
|  4 |  950.1 |  949.9 |  949.6 |  5 |  951.5 |  950.0 |  949.7 |
|  6 |  996.6 |  992.5 |  991.5 |  7 |  990.3 |  992.1 |  991.5 |
Totals (AMD):  7629.3 7624.8 7627.9 H/s
-----------------------------------------------------------------
Totals (ALL):   7629.3 7624.8 7627.9 H/s
Highest:  7643.3 H/s
-----------------------------------------------------------------

2.2
HASHRATE REPORT - AMD
| ID |    10s |    60s |    15m | ID |    10s |    60s |    15m |
|  0 |  976.9 |  974.4 |   (na) |  1 |  973.3 |  975.7 |   (na) |
|  2 |  944.9 |  947.6 |   (na) |  3 |  945.7 |  947.9 |   (na) |
|  4 |  970.4 |  980.0 |   (na) |  5 |  986.2 |  980.9 |   (na) |
|  6 | 1008.4 | 1008.8 |   (na) |  7 | 1009.3 | 1007.9 |   (na) |
-----------------------------------------------------
Totals:   7814.9 7823.2   (na) H/s
Highest:  7835.8 H/s

**Comment by psychocrypt** [comment]
thank you to all for the tests. I will skip this pull request and will first work on optimizations which will hopefully have a better effect on the hash rate.
