### ISSUE TITLE
Can I cap the CPU/GPU usage to like 20%?

### ISSUE THREAD

**Issue by BlackBip** [fireice-uk/xmr-stak#1120]
Everything is in titme.
Thanks

**Comment by psychocrypt** [comment]
Not explicit but you can reduce a few threads in cpu.txt to reduce the
system load

**Comment by BlackBip** [comment]
Thanks for that. Any way to reduce it a little bit more? Just trying to make my PC usable while mining.

**Comment by psychocrypt** [comment]
If you use a nvidia gpu incras bfactor this make all smoothet and reduce a
little bit the hashrate.
Check xmr-stak -h it is possible to disable the cpu or gpu mining. Test
both and found out if the gpu or cpu make the system laggy.

**Comment by JerichoJones** [comment]
xmr-stak --help

**Comment by tinsami1** [comment]
So that apps your actively using get more CPU time than xmr-stak:

If you're on Linux, you could execute xmr-stak at the lowest priority, i.e.: nice -n 19 ./xmr-stak

In Windows, you can lower the CPU priority after launching xmr-stak through the Task Manager's Detail tab -- right-click on xmr-stak and Set Priority to either "Below Normal" or "Low"
