### ISSUE TITLE
Stop/Pause when gpu temperature exceeds a threshold

### ISSUE THREAD

**Issue by crdkat** [fireice-uk/xmr-stak#1144]
Hi folks, I've already had this feature in my local machine. Just wondering if you guys need this, I'll make a PR.

**Comment by psychocrypt** [comment]
You can open it. But I am not sure if we should at such a feature. The
reasons are we need to support cpu, nvidia and amd gpus. This will at least
require 3 dependencies.
I also wrote it in an other issue, IMO this is a task for a monitoring
system like nagios, ...

Butnever the less I am interestwd how you implemented it. But please open
the PR only if you are not frustrated if it is maybe not accepted.

**Comment by nikl11** [comment]
This is a nonsence, temperatures are your problem, not miners. GPUs have thermal protection systems, which does already prevent any damage.

**Comment by pulsarcmc** [comment]
I'd be interested in this as well. What OS are you running / support? Which cards? etc..

**Comment by crdkat** [comment]
> This is a nonsence, temperatures are your problem, not miner's. GPUs have thermal protection systems, which does already prevent any permanent damage.

@nikl11 I assume that you just have only few rigs or you live in some cold weather countries and temperature stuff is not a big deal to you. I had 5 damaged GTX1080Ti few months ago (they're still under warranty). Also, my neighbor complained to me about noises and hot walls :smile: 

@psychocrypt I remember that the dependencies that I used already include in Linux Nvidia Driver.
@pulsarcmc Linux, Ubuntu 16.04. Nvidia card 9x or 10x
unfortunately, I'm quite busy for now. But if I have a chance, I will make a PR.

**Comment by Angel996** [comment]
We do need this system and I can explain why. 

I monitor rigs using tmux. Once I had a rig go into a weird state where ethernet port would chunks of repetative data, that clogged one of switches, so network got very slow, _yet connected_ (kinda of a local ddos). Turns out, tmux malfunctions in this situation: processes whose text output cannot be processed get terminated!

So I woke up that day to see some rigs heat up to almost 90C. Miners were running, while temperature script got terminated.

I run this stuff for almost a year, this has never happened, and I could have never imagined it was possible. So, **temperature monitoring must be tied to mining software, since it's the cause of heat.** Miner terminated = temperature monitoring terminated.

**Comment by psychocrypt** [comment]
Is it possible to solbe the root of the issue. Hardware is designed that
they can not get to warm. The system goa into throttling. It sounds be like
you have overclocked your system to much or changed the gpu bios.

**Comment by Angel996** [comment]
Factory shutdown temperature for most cards is around 95C. I usually run them at 65-70C. The reason they got overheated in my case is because fan control script got terminated because of tmux error. GPUs do shutdown at around 95C, but running @ 90C for a day is enough to fry the cards.

Temperature shutdown shouldn't be such a difficult mod I guess, I'm not asking to implement gradual intensity decrease by target temperature -- what most miners have today. Just shutdown at threshold temperature. AMD temperature can be found at `/sys/class/hwmon/hwmon$i/temp1_input`, NVidia - via CUDA I guess. (Sorry for trying to be a smart ass :-) )
