### ISSUE TITLE
multi-pool support enhancement

### ISSUE THREAD

**Issue by anhphan** [fireice-uk/xmr-stak#124]
We are already have multi-pool support, but we can make it better:

1. Accept pool with weight = 0, this pool will work when all other pool with weight > 0 die, it's failover pool as request of #123. This also the way most web server load balancing work.

2. When All user pool die, and dev pool still live, miner should mine on dev pool even fee ratio = 0. In this case web interface should have a red alert at top for user.

3. Slow down try reconnect failed pool, when I try 2 pool with weight ratio 100/1, and the first pool fail because wrong dns, I receive hundreds errors per second.

4. Connection tab should only keep 50 last network errors. In the test of about I have thousands of errors in connection tab, and web interface nearly hang when load that tab.

**Comment by fireice-uk** [comment]
1. Pool weight is purely relative. 0 needs special care not to crash the miner. Use weight of 1 and pretend that this is 0 =).

2. In that scenario the miner will idle to save user's power, unless the giveup limit is set, in which case it will shut down. I don't feel that using user's power simply because we have nothing better to do is a right thing.

3. ARGH! A very persistent bug. Thanks for reporting, will get it fixed.

4. Should not be a problem if the connection rate is not self-accelerating (see 3)

**Comment by fireice-uk** [comment]
Fixed in #127

**Comment by kim0** [comment]
@fireice-uk .. Thanks for your great work. Can you please clarify if pool_weight simply defines the percentage of time the pool receives the hash-power ? i.e. hashrate is simply allocated to different pools according to this weight factor? 

I'm asking bec of a confusing comment in the config file => Miner will mine mostly at the pool with the highest weight .. Which makes it sound as "failover" method.
