### ISSUE TITLE
feature request - support algo by block major version

### ISSUE THREAD

**Issue by DiscoTim** [fireice-uk/xmr-stak#1248]
With all the algo changes/forks in to the foreseeable future, as well as this project moving to support per coin. A thought is to define coin profiles, where the algo is defined/switched based on the block major/other criteria.
That's being done now (in an inflexible way) for the addition and maintenance of coins. the general idea something like..

```
coin_algos[] = { ...

{ "supercoingold",

  "algos": [{
    "blockMajor": 3,
    "algo":  "cryptonight_lite"
  },{
    "blockMajor": 4,
    "algo":  "cryptonight_aeon"
  },{
    "blockMajor": 5,
    "algo":  "cryptonight_gold"
  }]

}

```

**Comment by psychocrypt** [comment]
We also thinking about simplifying the fortk description but each coin can
have it's own changes.
Than one hard part is to avoid code duplication for gpu kernels. This is
not as hard for Cuda ( as long as there are no interface changes) because
we have templates bit Opecl is pure C and using the precompiler is not
maintainable.
