### ISSUE TITLE
create xmr stake 32bit version

### ISSUE THREAD

**Issue by zifootball** [fireice-uk/xmr-stak#1283]
please create xmr stake 32bit version

**Comment by Spudz76** [comment]
Less than 64-bit is too weak for crypto, and causes memory allocation headaches.  Even beyond that, lacking cache (Celeron/Atom) or AES-NI are nearly as pointless, even when 64-bit is available.

The only reason I can see for this would be because you want to be able to worm into 32-bit installs and not just be limited to trespassing and stealing from 64-bit other peoples servers.

If you own the equipment you would have 64-bit or be able to obtain it easily.

**Comment by JerichoJones** [comment]
No
