### ISSUE TITLE
Hashrate too low for CPU mining with the same config of the older version

### ISSUE THREAD

**Issue by diegogaulke** [fireice-uk/xmr-stak#1305]
After downloading the new version of xmr-stak (2.4.1) the CPU hashrate is very low.
The older version (Xmas bug fix release) is mining with hashrate 250 h/s.
With the same config in the new version the hashrate is about 75 h/s.
Using cpu core 0,2,4,6.

# Basic information
  - AMD Ryzen 5.
  - RX 570.
  - Windows 10
  - Large pages ok

**Comment by hd999ljh** [comment]
Same here..waiting for solutions.

**Comment by psychocrypt** [comment]
Both of you missing to provide full logs and all the configs. Anly to say
it is slow not helps to solve the issue.
Please fill out the issue template.

**Comment by psychocrypt** [comment]
Sumokoin increased the scratchpad memory for the hash to 4MB. Thats way you
**can not** compare old hash rates with new one. A derease to 50% is fine.
All miner will have lower hash rate with sumokoin.

**Comment by psychocrypt** [comment]
CPUs are limited by the cache. Most gpus has not used the full gpu.memory
because there was no benefit from it. This kind of gpus are now in the most
cases not slower. Some gpus which already run with full memory usage will
be slower now.
The good point about slowet cpus is that bot networks will have a hard time.

**Comment by JerichoJones** [comment]
Closing due to lack of response from OP.

**Comment by scryptkyddy** [comment]
I think that was intentional with Sumo to deter botnets from using cpu miners.
