### ISSUE TITLE
False? virus warning

### ISSUE THREAD

**Issue by DolphineCZ** [fireice-uk/xmr-stak#1316]
I am getting ?false? virus warning on xmr-stack-win64 

Windows Defender with repositiory as of 5.Apr 2018 reporting:

Trojan:Win32/Woreflint.A!cl in xmrstak_cuda_backend.dll
Trojan:Win32/Fuery.A!cl in xmr-stak.exe

**Comment by Spudz76** [comment]
Jackhats use xmr-stak, and other miner exes, in worms and such for mining for free on other peoples equipment, so they have all been cataloged as garbage.

It is only to protect normal (?) users that do not intend to have mining software on their computer.  Safe to ignore / whitelist it is purely a false notice by association because some people are doing it wrong.

**Comment by Jyewnidt** [comment]
man Windows defender is a real @$$, I've tried exempting the folder, the individual files, disabling WD completely. Still wont let me run it. It didn't bother @ all with my older versions...  Been @ it for 60 mins now.

**Comment by psychocrypt** [comment]
It is working when you exclude  a folder and download the zip directly into
this folder.

**Comment by Jyewnidt** [comment]
Awesome, I did this, however when i attempted to extract it, i did get a message stating it was getting deleted, however it was not. Thank you!

**Comment by payomagic** [comment]
anyway - the older versions are passing as clear / not to be used until the piece of garbage is removed. thx!

**Comment by scryptkyddy** [comment]
i recall seeing a registry script to disable/enable windows defender included with the nicehash miner legacy zip, you can find that by downloading "for amd" on nicehash's download site.
