### ISSUE TITLE
FileRepMalware

### ISSUE THREAD

**Issue by pfreindorf** [fireice-uk/xmr-stak#1321]
Just downloaded the 2.4.2 version (xmr-stak-win64.zip). My antivirus (avast) removed the exe and reported it as FileRepMalware ...

**Comment by Spudz76** [comment]
Tell it to ignore, obviously.

Not a virus / overactive imagination on the part of the scanners / there are mining-worms on the loose and average users aren't mining and would like it blocked if it happens to try and install.  You are not an average user it is protecting you overly.  You actually DO want things to mine on your computer... thus ignore/whitelist.

Same as you'll find most network inspection tools are ""virus"" detected because they can also be part of hacker garbage.  If you are the hacker, then you know to disable the protection.

I usually have a C:\miner\ and set that whole tree to be ignored.  Not too sure about the download protector stepping on you before you get it unpacked, though.
