### ISSUE TITLE
feature request -- support cryptonight/lite variant 1 as option

### ISSUE THREAD

**Issue by DiscoTim** [fireice-uk/xmr-stak#1326]
It would be useful if the variants of cryptonight, and cryptonight_lite were config options and could be used independent of block versions.

**Comment by psychocrypt** [comment]
Yes is maybe usefull but never the less the possibility change the
algorithm will be removed with the next release ( not needed after the fork)
Also Ineed to change the cryptonight heavy amd implementation first because
the version change is within the kernel.

Johnny Disco <notifications@github.com> schrieb am Fr., 6. Apr. 2018, 06:48:

**Comment by DiscoTim** [comment]
this looks like it, thanks :) https://github.com/fireice-uk/xmr-stak/pull/1375
