### ISSUE TITLE
AMD GPU intensive (remove please xmr stak)

### ISSUE THREAD

**Issue by ykutlu** [fireice-uk/xmr-stak#1338]
# AMD OpenCl issue
Please xmr stak Gpu intensive control disable. Your control, worked gpu slowed.
your control not need. Please remove. !!!

**Comment by psychocrypt** [comment]
I do not understand what you are saying. Please describe your problem and
if you have performace issue please use the issue template.

**Comment by perestoronin** [comment]
May be abount this?

>  "gpu_threads_conf" : [
>   // gpu: gfx900 memory:8048
>   // compute units: 56
>   { "index" : 0,
>     **"intensity" : 1792**, "worksize" : 8,
>     "affine_to_cpu" : true, "strided_index" : 1, "mem_chunk" : 2,
>     "comp_mode" : true
>   },
>

**Comment by perestoronin** [comment]
This option must calculate autoconfig, else, if manual selected, this reduce perfomance.
May be author of topic means return lazy custorm value 0 intensity as autoconfig for every start miner?

**Comment by Spudz76** [comment]
You can set -1 and it will automatic?
But probably not optimal / may even crash / you must tune and set correct for YOUR rig.
Automatic is only a starting point, it can never be everyone's favorite/best/opinion.

**Comment by ykutlu** [comment]
hi
thanks for interest
formerly vega64,
{ "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : false },
{ "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : false },
   working nice   
Device 0 work size 8 / 256.
Device 0 work size 8 / 256.

now
 WARNING AMD: gpu 0 intensity is not a multiple of 'worksize', auto reduce intensity to 1032.

 and if give 896 work and 
  working bad.  
Device 0 work size 8 / 32
Device 0 work size 8 / 32   ??? !!!

why 8/32 ???


my old gpu config, now not working
{ "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : false },
{ "index" : 0, "intensity" : 1932, "worksize" : 8, "affine_to_cpu" : false },

**Comment by Spudz76** [comment]
So follow the directions it gives and use two copies of this:
```
  { "index" : 0,
    "intensity" : 1936, "worksize" : 8,
    "affine_to_cpu" : false, "strided_index" : 0, "mem_chunk" : 2,
    "comp_mode" : false
  },
```
If you use worksize 8 , intensity must be 1920,1928,1936,1944,1952,1960 ... otherwise it will be guessed (like 1032) which is probably too small but will run (better to mine something than sit in error/launch loop which is ZERO hashes?)
There is little reason to use `comp_mode` when `intensity` is a multiple of `worksize`.
I changed `strided_index` to `0` because you are running stacked threads and the striding most likely is not helping then, and I also think it works worse on Vega anyway.

Unknown to me about the work size decisions.

**Comment by psychocrypt** [comment]
The initial problem is that the wrong config is used. You need to remove
amd.txt and let the miner generate a new config. Than tweak the intensities
in the new config.
