### ISSUE TITLE
Problem improving performance in XEON cpu,

### ISSUE THREAD

**Issue by pdelteil** [fireice-uk/xmr-stak#1508]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by Spudz76** [comment]
Zero Info

delete.

**Comment by psychocrypt** [comment]
@alexmateescu whichversion do you use. Coukd you please run `xmr-stak -V`

**Comment by psychocrypt** [comment]
Tested with the latest dev branch, sumo mining works fine up to low_power 4 (5 not tested)

**Comment by alexmateescu** [comment]
thanks for the info. sorry but i am a bit busy and did not have time to
follow the thread.

**Comment by alexmateescu** [comment]
Hi 

After multiple testing I found out that the issue only appears on intel cpu( I don’t have and to test) that are virtual.

On a physical host everything is fine on a heavy algo.

The also I am using is cryptonight_alloy. You have a pull request to merge the changes into the miner.

We are already using the miner with good results but as I said on a VM/VPS in order to make it work on CN_heavy or CN_alloy low_power_mode needs to be set to 1 in cpu.txt.

Any other setting 2-5, true or false gives rejected shares.

If there is anything else I could run to test I will do it gladly.

Regards

**Comment by psychocrypt** [comment]
I tested heavy yesterday with our current dev branch and all works fine.
Maybe you use an old codebase.
