### ISSUE TITLE
Non-reference Vegas 56 tagged with "Compute Units: 64" in auto generation of amd.txt

### ISSUE THREAD

**Issue by tpapaz** [fireice-uk/xmr-stak#1525]
# Basic information
- Type of the GPU
PowerColor RX Vega Red Devil 56

# AMD OpenCl issue
When running xmr-stak for the first time and the amd.txt is populating itself, it tags my 56 cards as 64.
-- // Compute Units: 64

Maybe in non reference cards, something has changed and the identifier read by xmr-stak is not there?

Other users reported the same using other brands of cards, e.g. Gigabyte OC RX Vega 56

**Comment by marcrblevins** [comment]
Would be nice if amd.txt listed the GPUs in chronological order as in Device Manager / Display adapters list.  That way we could track down problematic GPUs.

**Comment by psychocrypt** [comment]
xmr-stak used the order which is coming from opencl.
If the name is wrong than the opencl driver did something wrong but maybe
zou have a vega64 and you do not know it ;-)

**Comment by Spudz76** [comment]
Both issues are OpenCL's fault, complain to AMD.  xmr-stak shows them in the order and with capabilities OpenCL decides, which is what doesn't match.  May also be Microsoft's fault considering the devices show up in whatever random order they like, not based on location or PCI bus/slot at all ("device manager order" is wrong, sorry).  Best workaround is to use the OpenCL "Topology" reported (which is hopefully a normal bus:slot:device sort of tag, but Windows could goof that up too...) and sort card index by that... which would be no effect in Linux (as it does device ordering with sanity) but should reorder at least back to slot id (which is still rarely/never going to match physical order, most of my boards go 3,2,1,6,5,4,8 or such, and that information *can* be in DMI but sometimes isn't and sometimes is but is wrong.

So trying to 'fix' this may just scramble things worse, but it may be worth a try anyway.

Some V56 do indeed harbor V64 with bios disabling the additional.  But as far as I heard it takes bios mod to re-enable... should not magically occur.  I assume these additional compute units don't function even though they are reported?

**Comment by Spudz76** [comment]
Also even though Linux does ordering correctly, CUDA still mangles the order depending on some other factors.  So it's not just AMD or Windows where you have to backtrace PCI slot to ID to index.

**Comment by tpapaz** [comment]
@Spudz76 Indeed the opencl command output helps, although it tags every device as Compute Units 64.
*BUT*
There is a *Board name* field in each entry of the opencl command output that gives a value.
If the value ends in C1, it's a Vegas 64, if it's a C3 it's a 56 :)

**Comment by Spudz76** [comment]
Thanks for the useful info, trivial detection quirk/workaround can be added so autoconf fills 56 units for those name suffixes instead of what OpenCL reports.
The index ordering could be mapped to what the windows API reports (which is what all the tools you listed use).  But it should be an additional option within amd.txt requiring a new template however completely optional and default to regular/CL-order so existing configs (where user doesn't care) just continue to operate as they always did.  Changing the setting would result in windows indexing, and would not be the default.  I believe it also requires a chunk of code for probing that currently does not exist.  This device ordering remap feature should also be applied/available to CUDA since there are similar issues there with mixed cards (it seems to order them equally when all are the same compute levels, though).

**Comment by tpapaz** [comment]
Whoa that would be awesome.

Thanks for even considering this!
