### ISSUE TITLE
Is cmake necessary? Cmake pulls in a lot of useless dependencies.

### ISSUE THREAD

**Issue by Avispa** [fireice-uk/xmr-stak#1529]
As the title already opens up: is _cmake_ really necessary for **xmr-stak**?

At **least** it pulls in QT as a dependency for no real reason.
´´´-- OSX_VERSION='10.13.4'
-- Could NOT find Qt4 (missing:  QT_QMAKE_EXECUTABLE QT_MOC_EXECUTABLE QT_RCC_EXECUTABLE QT_UIC_EXECUTABLE QT_INCLUDE_DIR QT_LIBRARY_DIR QT_QTCORE_LIBRARY) 
-- Warning, could not run java --version
´´´
Just cmake itself uses it to process it cmake files.

´´´
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURSES_CURSES_H_PATH
   used as include directory in directory /xxx/src/cmake-2.8.6/Source/CursesDialog/form
   used as include directory in directory /xxx/src/cmake-2.8.6/Source
´´´
Also curses gets pulled in on OSX even though it should be installed. However, xmr-stak (and I) do not need curses.

Maybe I can fix the curses error from the site of cmake BUT the main question is why using a sledge-hammer...? Why to pull in that heavy tail of dependencies just for (c)make?

**Comment by Spudz76** [comment]
I have never had CMake depend on anything ridiculous (Linux, Windows).
I doubt this project would build as easily as it does on various platforms with a generic canned Makefile.
Shall we switch to 'autoconf' ???  I thought CMake is just another Autoconf (but better!)

**Comment by Avispa** [comment]
> I thought CMake is just another Autoconf (but better!)
Better in which sense?

I don't have enough insides into **autotools** nor **cmake** to give a qualified answer to that but I would consider cmake more complex (in solving build problems but also within itself) and by that I'm pretty sure it depends on the project. So by going with that, maybe wrong but at least uneducated assumption, I would choose for a somehow simple program **autotools**; while for a complex one, maybe as like as eclipse IDE, **cmake** could be reasonable.

At the point at which the build tool looks more complex than the actual build target I would reconsider my choice -- and by complex for sure I mean dependency trees and build complexity rather than function/arithmetic complexity.

What was your reason to choose **cmake** over something else?

**Comment by Spudz76** [comment]
I was not here so I'm not sure, however I think other alternatives wouldn't work as zero-maintenance on OSX or Windows, or would require more manual provision of where libraries were located versus user convenience of them being located automatically (and then in some cases further probed to for example forcibly ensure AMD OpenCL libs when the system tries to offer Mesa, nVidia, or Intel ones first or by default.  It handles automatically compilers as well, where CUDA requires some other compiler for its section different than the CPU and OS.  But mostly all the things it brings for generating the VC++ project files for MSVC compiler to eat.  Nobody's going to maintain those in a static form.

There is no group of volunteers to test canned Makefiles (if say we'd prefer a `Makefile.OSX`, `Makefile.Windows7` ... Windows10 ... LinuxUbuntu14 ... LinuxUbuntu16 ... etc) and that takes a maintainer as well to ensure they continue to work when dep versions change or desired project-wide compiler optimizations need adjustment with one line edit.  If this were imported to Distro then the maintainer of such packaging would be the one to generate a Makefile and "Debian-ize" it as needed from the CMake sources, so that dpkg source builds would not need CMake (it can specific-target given a... specific target?).

But nobody here cares to maintain even example Makefiles, there is plenty of work to keep on top of all the pool-bugs and coins and forking around (heh).

If this were a UNIX-only sort of thing then no, it would be somewhat useless to have CMake around.

**Comment by psychocrypt** [comment]
Yes CMake is necessary. Cmake has no dependencies to QT if you not build
the cmake-gui.
CMake is the modern build gernerator. Autotools is OK but outdated and
complicated.
CMake allowes us to provide the miner under windows, linux, bsd and osx.

**Comment by Spudz76** [comment]
Also check for `*-nox` packages in Debian-like (Ubuntu, etc)
Such as `hwloc-nox` which is the no-junk command line only `hwloc-ls` command
Maybe there is a cmake-nox (or explicitly forbid the cmake-gui from being dragged in by pinning?)
