### ISSUE TITLE
Failed to read xmr-stak from localhost /HTTP Daemon failed to start

### ISSUE THREAD

**Issue by Abrustetha** [fireice-uk/xmr-stak#1536]
randomly getting errors with XMR stak

running Hiveos

and I on and off get HTTP Daemon failed to start in the miner
the agent screen says failed to read XMR stak from localhost

after a few reboots it works again.

only when i make a wallet change or a fan change then the problem comes again.

# Basic information
  - Celeron G3900
  - RX 550s

  ```

**Comment by Spudz76** [comment]
I suspect something with the HiveOS process control is not bothering to actually await the old xmr-stak process(es) exit and complete release of resources, and tries to fire the next one up whilst the old one is still shutting down (some of my more esoteric rigs can take 30 seconds to actually exit... de-initializing the GPU contexts or whatever it is doing, I'm not sure).  Sometimes it won't exit whatsoever and I have to reboot but that's hardware error (too much OC, bad power, bad cooling, etc - real crashes where driver gets hung totally).

If nothing checks and it just requests quit and then blindly sleeps 10 and relaunches it won't always work out.  It literally must sit and await all old PIDs until they leave before firing up the next.

It may work smoother considering the Celeron and usually those having low cache, to not mine on CPU and only on the GPUs.  I've never seen/used HiveOS so I'm not sure if it would automine with everything available just because it's available and not because it's worth it.

**Comment by Abrustetha** [comment]
i recompiled the kernel to work with the rx 550.
its not a driver issue becasue the cards work and hash. randomly i get HTTP Daemon failed to start errors.

**Comment by JerichoJones** [comment]
Unless I'm misunderstanding this is a Hiveos issue.
