### ISSUE TITLE
The program hangs on this part

### ISSUE THREAD

**Issue by jptsaikoski** [fireice-uk/xmr-stak#1570]
- AMD A6-3500 APU
  - AMD Radeon HD 6530D
  - Windows 10 64-bit
  - 8GB RAM

> [2018-05-16 21:16:09] : Mining coin: monero7
> WARNING: NVIDIA Insufficient driver!
> [2018-05-16 21:16:09] : WARNING: backend NVIDIA disabled.
> [2018-05-16 21:16:09] : Compiling code and initializing GPUs. This will take a while...
> [2018-05-16 21:16:09] : Device 0 work size 8 / 32.
> [2018-05-16 21:16:09] : OpenCL device 0 - Load precompiled code from file C:\Users\JPTS\AppData\Local/.openclcache/*******************************************************************************
> [2018-05-16 21:16:09] : Starting AMD GPU (OpenCL) thread 0, no affinity.
> [2018-05-16 21:16:09] : Starting 1x thread, affinity: 0.
> [2018-05-16 21:16:09] : hwloc: memory pinned
> [2018-05-16 21:16:09] : Starting 1x thread, affinity: 1.
> [2018-05-16 21:16:09] : hwloc: memory pinned
> [2018-05-16 21:16:09] : Starting 1x thread, affinity: 2.
> [2018-05-16 21:16:09] : hwloc: memory pinned
> [2018-05-16 21:16:09] : Fast-connecting to pool.supportxmr.com:3333 pool ...
> [2018-05-16 21:16:10] : Pool pool.supportxmr.com:3333 connected. Logging in...
> [2018-05-16 21:16:10] : Difficulty changed. Now: 5000.
> [2018-05-16 21:16:10] : Pool logged in.
> [2018-05-16 21:16:10] : New block detected.

The program hangs on this part and does not continue, what should I do?

**Comment by Spudz76** [comment]
Terascale don't work very well with drivers newer than 15.12 or so

Which also means no Win10...

I run my Terascale junk on Debian Trusty (ancient!) with `fglrx` driver (also ancient).  Anything newer was flaky at best (including hangs like you describe).

You may have even more trouble, because that is a Sumo with 80 disabled shader units (aka embedded and hobbled) and may be sort of an edge case (so AMD-Software + Edge-Case = probably problematic).

Not sure if it's using discrete memory (GDDR?) or shared system ram in which case you'll hate the hashrate even if it did work.

**Comment by Simaex** [comment]
Terascale run pretty well on Windows 10. But you need to install 14.4 driver to get normal performance. In case you need some help you should follow issue publishing guidelines. In you case it seems that no use to fiddle with HD6530D integrated video core. You will not get any better results then for CPU only mining so just disable GPU as the first troubleshooting step.

**Comment by Spudz76** [comment]
I stand corrected - I guess the old Win7 drivers work with 10 somehow.

**Comment by JerichoJones** [comment]
@jptsaikoski Please use the template. This is not enough information.
