### ISSUE TITLE
Linaro?

### ISSUE THREAD

**Issue by gokart2** [fireice-uk/xmr-stak#1574]
There is no issue. Could not find how else to contact. 

Can Linaro GCC's be used for compiling? I for the life of me tried installing from [here](https://releases.linaro.org/components/toolchain/gcc-linaro/), but was unable too, Ubuntu 17.10. 
And/or on Win 10?

**Comment by psychocrypt** [comment]
I have never tried it.

**Comment by gokart2** [comment]
Always benefitted from Linaro in the past with Android kernel compiling. Both feel of the devices and benches. Much more of a pain compiling because of how strict it was with warnings/errors. But there's so much less code with xmr-stack, don't think it'll be nearly as hard to compile without errors.

Now, that was using a specific toolchain for Android compiling. Not sure if using the Linaro specific GCC's would benefit like the toolchains. Was just an idea for a possible optimization increase.

BTW, thanks for all your guys work. Greatly appreciated!

**Comment by Spudz76** [comment]
You may run into forced `-maes` and `-msse3` trouble if you are cross-compiling (to non-amd64).
This compiles with those enabled regardless of actual CPU or compiler.

I have seen +2H/s on CPUs using clang-3.8 rather than gcc / however gcc 6.4.x is faster than clang-3.8 on some CPU types.  But it supports those same two required `-m` flags and thus ends up working.  If the Linaro is strange or doesn't like being forced to generate aes+sse3 code when native mode disagrees...
