### ISSUE TITLE
1080Ti pair get 368 error nearly right after starting.

### ISSUE THREAD

**Issue by Kettoch** [fireice-uk/xmr-stak#1584]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - I9-7920X
  - 2x 1080tI

# Compile issues
  - Which OS do you use?
 Windows 10 Version	10.0.17134 Build 17134

# Issue with the execution
  - Do you compiled the miner by our own?
No
# Stability issue
GPU is overclocked but does the same regardless.

xmr-stak 2.4.3 26a5d65f

Brought to you by fireice_uk and psychocrypt under GPLv3.
Based on CPU mining code by wolf9466 (heavily optimized by fireice_uk).
Based on NVIDIA mining code by KlausT and psychocrypt.
Based on OpenCL mining code by wolf9466.

Configurable dev donation level is set to 2.0%

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2018-05-19 22:30:20] : Mining coin: monero7
[2018-05-19 22:30:21] : Starting NVIDIA GPU thread 0, no affinity.
[2018-05-19 22:30:21] : Starting NVIDIA GPU thread 1, no affinity.
[2018-05-19 22:30:22] : Fast-connecting to us-east.cryptonight-hub.miningpoolhub.com:20580 pool ...
[2018-05-19 22:30:22] : Pool us-east.cryptonight-hub.miningpoolhub.com:20580 connected. Logging in...
[2018-05-19 22:30:23] : Difficulty changed. Now: 40000.
[2018-05-19 22:30:23] : Pool logged in.
[2018-05-19 22:30:23] : New block detected.
[CUDA] Error gpu 0: <C:/xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu>:368

"gpu_threads_conf" :
[
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9309/11264 MiB
  //      smx: 28
  { "index" : 0,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9309/11264 MiB
  //      smx: 28
  { "index" : 1,
    "threads" : 54, "blocks" : 84,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false, "sync_mode" : 3,
  },

],

**Comment by Spudz76** [comment]
That's line 368, or: [here](https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu#L368)

Did you enable large/fast memory (policy edit) as it says to do in both the docs and the config.txt?  Are you using a normal crytonight coin, or Heavy?

Auto tuning is likely selecting too many blocks because you have "ridiculous" amounts of VRAM (you should really be mining ethash or such, with a card like that, you will run out of crunch power at less than a fifth of the VRAM used...)

1080Ti probably also work better like Vegas and do multiple host threads to each GPU, I'd do 54:14 thread:block and around 6 entries (host threads) per card.  Which works to the same 54:84 total but uses 6 parallel 'pipes' to each GPU instead of one.

**Comment by Kettoch** [comment]
This is what worked

  {
    "index": 0,
    "threads": 128,
    "blocks": 28,
    "bfactor": 10,
    "bsleep": 100,
    "affine_to_cpu": false,
    "sync_mode": 3,
  },
  // gpu: GeForce GTX 1080 Ti architecture: 61
  //      memory: 9309/11264 MiB
  //      smx: 28
  {
    "index": 1,
    "threads": 128,
    "blocks": 28,
    "bfactor": 10,
    "bsleep": 100,
    "affine_to_cpu": false,
    "sync_mode": 3,
  },
],

**Comment by Spudz76** [comment]
Interesting, I didn't ever get over 64 threads to work on anything I used.
