### ISSUE TITLE
AMD Backend unable to be found

### ISSUE THREAD

**Issue by BonitaTerror** [fireice-uk/xmr-stak#1586]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
Intel i3
  - Type of the GPU (if you try to miner with the GPU).
AMD Radeon 570
this is with fedora 28 xfce

# Issue with the execution
  - Do you compiled the miner by our own?
  ``` 
yes
  run `./xmr-stak --version-long` and add the output here
  ```Version: xmr-stak/2.4.3/26a5d65/master/lin/amd-cpu/aeon-cryptonight-monero/0


# AMD OpenCl issue

  run `clinfo` and add the output here
  ```clinfo: error while loading shared libraries: libOpenCL.so.1: cannot open shared object file: No such file or directory

I have installed AMD APP SDK from a mirror link that was on another issue and it now resides in /opt. I am rather noobish at linux and I am not sure what could be going wrong or how to fix it so any help is greatly appreciated

**Comment by BonitaTerror** [comment]
I have some extra information. It is possible that the version of the AMD SDK I am using installs with a broken symlink. I read another thread here https://community.amd.com/thread/207141 that seems to be describing problems that some people here have been having. Unfortunately their solution involves that broken link that goes to a 404. So I'm still uncertain what should be done. I just thought this extra info might help us along :)

**Comment by Spudz76** [comment]
That AMD thread is talking about the 3.0 Beta whereas you already have the Release version, linkage problem should be gone.

`updatedb` then `locate libOpenCL.so` should show a library in `/opt/amdgpu-pro/lib/x86_64-linux-gnu/`...

Try adding
`-DOpenCL_INCLUDE_DIR=/opt/AMDAPPSDK-3.0/include -DOpenCL_LIBRARY=/opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so`
to your cmake line and see what it does

**Comment by Spudz76** [comment]
Oh, okay, it looks like you don't have the AMDGPU-Pro driver at all.
Fedora is nearly the most difficult Linux to install it on... but may work better with the 18.x driver.
[AMD Driver for Linux](https://support.amd.com/en-us/kb-articles/Pages/Radeon-Software-for-Linux-Release-Notes.aspx)

If you want a simpler and nearly plug and play experience without learning Linux to uncomfortable depths, use Ubuntu 16.04.3 otherwise it will be too new/uncharted to get any sort of help online.

**Comment by BonitaTerror** [comment]
Thank you. I downloaded the compressed files from the link you sent and extracted them. Then I attempted to run the install but I am getting:

No match for argument: amdgpu
Error: Unable to find a match
./amdgpu-install: line 70: dkms: command not found
WARNING: amdgpu dkms failed for running kernel

I also had just updated dnf

If this doesn't seem like an easy fix I am pretty willing to switch distros, but I just wanted to check first

**Comment by Spudz76** [comment]
`dkms` is mostly a Debian thing, the RedHat equivalent is known as `dracut` and the AMD package doesn't support it.  Not sure which one but the RHEL packages are the closest to Fedora but not exact, they might know dracut instead but still may not work.

Very few people have bothered to use RedHat for mining, that distro is more for super stable (but kind of old) web hosting and not much else.  Definitely not the distro for stuff just working, or hardware you'd never expect to see in a datacenter (GPUs) for serving web pages.

You've selected the industrial Linux (big diesel truck, RedHat) whereas all the mining stuff is geared for consumer/gaming Linux (sports car, Ubuntu).

**Comment by Spudz76** [comment]
[This](https://www.reddit.com/r/Fedora/comments/89q8w7/amdgpu_support_for_fedora_27/) is apparently how Fedora works, you run the Open Source driver (one it comes with) and then manually install the OpenCL parts of the Pro driver by extracting the installer package and copying some files out of it (not using the script).

**Comment by BonitaTerror** [comment]
Okay. I appreciate all this help. Thanks again, but I think I've been broken and I want to give Debian or Ubuntu a shot :joy: would you have a recommendation as to which?

**Comment by Spudz76** [comment]
Ubuntu-16 however people seem to have good luck with Ubuntu-18 as well.
I have not tried Ubuntu-18 yet.
Debian is somewhere in between the diesel and the sport, and has some incompatibilities compared to the drivers which are all (AMD and nVidia) designed for Ubuntu.  So best to go with what all the drivers support, Ubuntu-16.   I use the Server version although Desktop should also work fine, and would be what to use if you are also using the rig as a computer (all mine are dedicated mining rigs, headless)
If you go Ubuntu-18 then you will only be able to choose from the newest AMD-18 driver and not AMD-17.50 or AMD-17.40 or previous.
Again people seem to be using the latest of both to success but I have personally been burned too many times by not running slightly old software for mining specifically.  Too many layers for everything to catch up on, so by running the older but proven driver on older but proven Ubuntu with latest miner apps you generally get good compatibility.  Takes the apps some time to catch up on the new bugs, in the new drivers, on the new kernels, etc.  Trickle down but also somewhat on peoples spare time.
Also as I mentioned before the amount of reference information on message boards will be larger for the older things as well.  New and latest stuff either doesn't have reports yet (few attempts), sometimes is the same as the older versions, but sometimes is a mystery to solve alone due to no information yet (nobody else tripped on the easy bugs).
You should be fine on Ubuntu-18 with AMD-18 with the RX or Vega cards but older generations tend to be better with the driver+OS that was around when the hardware was relevant (despite still supporting old hardware in new drivers, it isn't always as fully proven / partly abandoned / about to be removed etc).

**Comment by Spudz76** [comment]
I have an RX550 and run the 17.50 driver on Ubuntu 16.04.3 (kernel 4.13), it is supported.  I think it also worked in 17.40 but not quite as well, and was missing some clock/fan control stuff if I recall correctly.
If you use the newer installer media (16.04.4 or 5) it will put you into the newer kernels and may not work as easily with the full range of driver selections.  Use 16.04.3 iso to lock the system into the more compatible kernel range without manually reverting.  It also works with the AMD-18 driver.

**Comment by BonitaTerror** [comment]
So I switched over to Ubuntu 18 and it appears I am getting farther as far as amd drivers are concerned, but I am now getting issues with compile so I am going to close this issue and put the new stuff in a new one if I can't find a solution in the others, since it's not really relevant to this one. Thank you!
