### ISSUE TITLE
Miner closes after start with no errors

### ISSUE THREAD

**Issue by DoDoSt** [fireice-uk/xmr-stak#1611]
![xmrstackissue](https://user-images.githubusercontent.com/22191649/40785354-976cff92-64e8-11e8-8ce8-672e6ab97b5e.png)

# Basic information
  - Intel i7-7700K
  - NVIDIA GeForce GTX 1070

# Compile issues
  - Windows 10 Pro 1803

# Issue with the execution
  - When I start the miner i closes itself after "Starting NVIDIA GPU thread 0, no affinity."
  - I tried version 2.4.3, 2.4.4 
  - I tried both: build downloaded from here and locally build from sources
  - Version 2.4.2 is working with the same settings

Can I see some more logs from the miner? I only see the last info line as shown in the picture and no errors.

**Comment by DoDoSt** [comment]
[config.txt](https://github.com/fireice-uk/xmr-stak/files/2058701/config.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/2058702/nvidia.txt)
[pools.txt](https://github.com/fireice-uk/xmr-stak/files/2058703/pools.txt)

In pools.txt I deleted my wallet address and password.

**Comment by psychocrypt** [comment]
do you removed the wallet adress from the pool.txt or do you missed to add
it

**Comment by Spudz76** [comment]
What driver version?

**Comment by DoDoSt** [comment]
NVIDIA driver version is 397.93.

**Comment by Spudz76** [comment]
Should be good though it is new (I'm still on 397.64 Win7 which works nice for GTX970 - the 396.xx were so broken they aren't even listed in historical downloads on their site).  I would be tempted to run the last CUDA 8.x driver, and then the release versions should work, but if you compile you'd need to use the 8.0 SDK.

When you built your own, was it CUDA 9.x based?

I have some patches awaiting acceptance which will show detail about runtime+driver CUDA versions to help figure out exactly whats happening in cases such as this.  CUDA 8 apps will run against the CUDA 9 driver but is it really best and reliable - probably not.  I prefer to keep everything the same level.  There are no gains to be had using CUDA 9 anyway, all performance enhancements are for stuff we don't use mining / only for the AI and science goofballs.

**Comment by DoDoSt** [comment]
I added your xmr-stak/xmrstak/backend/nvidia/nvcc_code/cuda_extra.cu file to my local build and got this log now:
![xmrstakissue](https://user-images.githubusercontent.com/22191649/40795846-87822bdc-6503-11e8-8757-b3d11ce4bf2a.png)

I'm on CUDA 9.

**Comment by Spudz76** [comment]
Okay so that is showing the driver @ 9.2 and you compiled with the 9.1 SDK.  The 9.2 SDK is available now, perhaps there is some room for bugs between 9.2 driver and 9.1 client.  If you can get that to show 9.2/9.2 after updating SDK and rebuilding, it may work better.  The 397.64 driver is still 9.1 so you might give that a try first (get it to show 9.1/9.1) as it is easier to shift drivers around than SDK, and if it were a 9.2 vs 9.1 issue then it should work at 397.64 and then more confident getting matching 9.2/9.2 would also succeed.  Then it's a CUDA bug, which is what it seems like, although very odd it doesn't error and just exits.

What about if you run it without the `.\` just xmr-stak.exe, I was pretty sure that was not necessary on Windows (you can't remove `.` from the path, it's assumed) and may be making it do something weird.

**Comment by DoDoSt** [comment]
nvidia-smi gives me:
![nvidia-smi](https://user-images.githubusercontent.com/22191649/40814781-b196bd90-6542-11e8-8bc4-033599427d80.png)

I updated cuda and now I'm getting 9.2/9.2 :
![xmrstackissue](https://user-images.githubusercontent.com/22191649/40814867-1b1d4b12-6543-11e8-983a-74cafa8343ff.png)

As you can see, I also tried without .\

**Comment by psychocrypt** [comment]
It looks like an driver issue because there is not report that something is
crashing. Is it possible to test cuda 8?

**Comment by DoDoSt** [comment]
I'm now on NVIDIA driver 376.51 and cuda 8 getting still the same behaviour: 

![issue](https://user-images.githubusercontent.com/22191649/40827963-96b399a2-657f-11e8-97e5-c7db13e5121d.png)

**Comment by Spudz76** [comment]
Still very strange, does anything show up in Windows Event Viewer?

**Comment by Spudz76** [comment]
How about running with `--noCPU` and `--noAMD` so as to force it to not even load/probe those.
I notice you have no cpu.txt and no messages about it, but aren't apparently using `--noCPU` so it may be dying there?

**Comment by DoDoSt** [comment]
I forgot the cpu.txt. It isn't generated if you start the miner from scratch and enter the pool parameter etc. ? 
Now I added the cpu.txt manually and the miner quits still in the same way.

The idea with the windows event log is pretty good. There are errors. I found "Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igdrclneo64.dll" (sry, my system is german). But we see, there is something with amd! And I have no AMD GPU. So I tried --noAMD and here we go, it works! Thank you very much! Next time I will know about the windows event log.

**Comment by Spudz76** [comment]
Yes `cpu.txt` is generated but only if execution doesn't stop when loading OpenCL DLLs.  It was dead before it could look at cpuinfo and make the file.

Also that is not AMD driver, it is Intel iGPU OpenCL driver, which xmr-stak will attempt to load in order to ask it who its manufacturer is, unless you use `--noAMD` (which really means --noOpenCL).

"amd64" there in the INF path is just your 64-bit arch OS tag.  So you do have Intel drivers installed...

You may prefer to compile with `cmake -DCMAKE_BUILD_TYPE=Release -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF ..` as that will waste less build time and not even have the GPU code so then you need no runtime options (cpu-only executable).
