### ISSUE TITLE
compressedDL extraction unsuccessful, No EXE file

### ISSUE THREAD

**Issue by ElecDanOT** [fireice-uk/xmr-stak#1627]
disabled defender, firewall and Mcafee before DL
 download appears successful go to extract and all I get is a new file (xmr-stak-win64) with only two items, libeay32.dll and ssleay32.dll

no exe file?!
tried with chrome and edge, same issue

any guidance appreciated... 

windows 10 pro
XPS 8300
I7-2600 @3.4 GHz
12 RAM
64 bit 
AMD Radeon HD5700

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?

  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by Spudz76** [comment]
Leave antivirus off during unzip not just download.  Also make `C:\miner\` or wherever and set as whitelisted with subdirs in all antivirus/defender junk and then extract into `C:\miner\xmr-stak-win64\` and it should leave you alone.  Otherwise whenever you have the stuff turned back on it's going to delete the exe any time it sees it.
