### ISSUE TITLE
How to reduce power utilization of my GPU (nvidia)?

### ISSUE THREAD

**Issue by SkyDr4k3** [fireice-uk/xmr-stak#1633]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - 
  - 1050TI.

# Compile issues
  - w7 64bit

**Comment by Spudz76** [comment]
`nvidia-smi -i 0 -pl 10`

**Comment by SkyDr4k3** [comment]
where do i have to write it? ty btw

**Comment by Spudz76** [comment]
See screenshot, you do from `cmd.exe` and `cd` to directory shown

![image](https://user-images.githubusercontent.com/2391234/40946512-2be28f9a-681b-11e8-8f77-a8e87c2e2987.png)

output of command with no args shows current usage and limit (50W / 170W on mine at the time of the pic)

I typo'd above the 10 should be 100 as you see it doesn't accept below a certain power limit, but that could be different on different cards (970 vs 1050) so I would give it -pl 10 and let it tell me the minimal watts and then use that.

It will of course hurt the hashrate, but by moving that limit around you can find a trade off point.  Usually in the 70% to 80% range on 10xx series.  You can clock up your memory to max-not-crashing to get back some of the lost to save power hashrate (raised memory speeds make little difference to watts as long as voltage is not raised to stabilize high clocks or such) but... for clocking there is also an issue with Windows and 10xx where they lock into "P2" mode whenever a CUDA or OpenCL app fires up, you need a thing called `nvidiaprofileinspector` and that lets you flip the internal undocumented P2 lock disabled, so that it will run in P0 with compute apps.  But, that should actually save power if you leave it in P2 lock (lower clocks generally).  But sometimes depending on cards VBIOS it is also impossible to change clocks in P2 mode whereas P0 can be changed.  So you may want to get P0 mode just to be able to under-clock GPU core farther than P2 to save power, and clock up the memory, depending on how aggressive you want to be.

But I think the driver built in powerlimit works well at balancing it all for you.  I'm not sure how accurate its wattage measurement really is, versus a meter on the wall socket.  Also if your PSU gets more efficient with less watts drawn, the overall at-the-wall AC consumption could be lower by some factor beyond just the raw DC rail watts shown in `nvidia-smi` output.

**Comment by Spudz76** [comment]
Your 1050 should show P8 or such (next to the power usage/cap where screenshot of mine shows P0) when idle, and possibly P2 while xmr-stak is running.  Then with P2-lock disabled it would show P0 while xmr-stak is running, and you should be able to edit clocks in whichever clocking app as well.

P2 usually brings down the memory rate quite a bit which is what we want to leave as high as possible (for cryptonight and variants).  But then also for watts you'd want to bring down the core clock probably.

**Comment by SkyDr4k3** [comment]
thank you but it is too difficut for me. I thought it was easier like adding a command line to the config file. I study law, not computer science.

**Comment by Spudz76** [comment]
The nvidia-smi powerlimit setting should do what you want, superficially.  The rest of the complex stuff was just to squeeze the last few hashes out of the reduced watts, likely not worth it anyway.  Setting driver power limits will reduce power usage, it's just not the most effective method by itself.
