### ISSUE TITLE
Feature request: add Intel GPU OpenCL support

### ISSUE THREAD

**Issue by Zenitur** [fireice-uk/xmr-stak#1640]
For Linux, there are few realizations of OpenCL for Intel GPU:

1. An official closed source realization: https://software.intel.com/en-us/articles/opencl-drivers It perfectly working on Ubuntu 16.04.x without any patching, but needs the patch if your Linux distribution is not Ubuntu. [clinfo output](https://pastebin.com/jqEawMqP)
2. Beignet (Mesa Classic)
3. Clover (Mesa Gallium)

It will be nice if anyone of these will appear in xmr-stak!

**Comment by Spudz76** [comment]
Mesa/Clover currently coredumps just from us attempting to query its capabilities, maybe even just loading the ICD before asking it anything.  Good software!  Beignet who knows, probably the same quality went in before the name went on.

Proprietary in Windows crashes (again on probe) with no dialog boxes and takes the whole exe down with it, just for being in the ICD list.  More good software anyone would love to be involved with.

I think the proprietary on Ubuntu might work OK.  But you'd be better off using the CPU backend as none of the iGPU really gain anything (still chugging across system RAM, slow compared to real GDDR5 locally).

Of course since it had barely ever worked we don't know for sure it wouldn't be worth it, but it sure seems like it wouldn't.  Unless Intel is about to release some real GPUs, not integrated, and around 4x faster than any of their historical creations.  Same reason there is no engine swap kit for a Geo Metro 3cyl into a Chevy Suburban.  Why bother / no market / would be laughable joke except as proof of concept exercise.

There was a PR here somewhere a while back with movement toward adding Intel, it stalled, but I think did get some parts working better.  But then since that the OpenCL backend code has changed (to add nVidia-via-OpenCL support for the 10 cases where that is faster than CUDA) and other code changed as well (for algos) so it is likely not a clean apply anymore.  But Intel could be added now similar to how nVidia was (alternate manufacturer select), so there is a framework for that which also flags the code to disable AMD-specific CL extensions.

**Comment by Spudz76** [comment]
Some Intel IGD may not use system RAM, they use the CPU cache up until you run that out of space.
But then there is little cache for the actual CPU, and you can't CPU mine simultaneous at all, which is how it works out better to just CPU backend and forget IGD/CL.  You lose 100% of any CPU hashes to gain generally less hashes out of the IGD.

**Comment by Spudz76** [comment]
PR #1112 is the one wherein some Intel test/fix happened.

**Comment by Zenitur** [comment]
When I saw non-AMD support in master GIT, I'd tested it with an old NVIDIA 9800GT. `./xmr-stak --noNVIDIA --openCLVendor NVIDIA`. I'd got 60 h/s on this GPU. This is nice for me!

Also I mine on a notebook. CPU: 100 h/s, NVIDIA GPU 122 h/s. I don't know how much hashes can get Intel HD 4000

**Comment by Zenitur** [comment]
Thank you for your reply! It's big and good

**Comment by Zenitur** [comment]
Also there is OpenCL on Raspberry Pi's GPU.

[How to install OpenCL on Raspberry Pi](https://github.com/doe300/VC4CL/wiki/How-to-get)
[Not supported functions](https://github.com/doe300/VC4CL/wiki/NotSupported)
[clinfo output on Pastebin](https://pastebin.com/aQtG1UcT)

**Comment by bcheeves** [comment]
I really think this would be a useful feature to add for a few reasons:
1) Intel is manufacturing their own high end GPU's now
2) The integrated GPU's in the latest generation processors are designed to compete with the AMD vega GPU's in amds ryzen series processors
3) apple stopped shipping macbook pro models with amd or nvidia discrete GPU's, now it's only intel.
4) the latest apple models, that are arm based, come with an intel GPU as well 

I'd be happy to test compilation of the code and run it on my MacBook Pro 13" 2020 model.  As it stands right now, I tried to modify the code to have it recognize the intel GPU and run on it, but I think that I made a mistake somewhere. 

Has anyone tried making a patch that will work with intel GPU's for testing? I realize that my iris pro graphics may not be as powerful as an AMD or Nvidia chip, but it has plenty of cores, 1.5 GB of dedicated VRAM and I believe it's around 850 mhz base clock frequency.  I am pretty sure I could mine some lighter algorithms at least, and if nothing else, I love to do hashing benchmarks as performance test, and it's helpful in debugging software if you can actually run it on my MacBook, just the same as my PC.

**Comment by bcheeves** [comment]
I just realized that PR#1112 implies it will work with intel igpu.  I had tested similar config with a fermi based nvidia card previously. I will try it out on my intel iris pro, just for curiosity sake mostly. Thanks.

**Comment by Spudz76** [comment]
I only ever got it to work on [Gen7](https://en.wikipedia.org/wiki/List_of_Intel_graphics_processing_units#Gen7) or newer, anything older won't OpenCL at all.  And even then it was not worth it.  The iGPU uses CPU cache so using the GPU destroys the hashrate of the CPU, without adding enough speed.  If it doesn't fit in cache then it uses shared system memory which is of course a bottleneck compared to GDDR5 or HBM2 on a "real" GPU, leading to garbage hashrate.  In summary, it hasn't been worth it yet, maybe the latest discrete GPUs from Intel will be different but also not expecting them to be great.

Also of note in the OpenCL support column in the link above: MacOS never gets above 1.2 while Windows/Linux get upgrades.  Newer MacOS no longer has OpenCL but instead a dumb emulation layer that doesn't work, called CL2Metal... Nobody has bothered to try writing miners directly for Metal since they would only be useful on MacOS (if they work at all).  Apple should not have abandoned OpenCL unless they were going toward VulkanCompute or whatever is industry standard, instead they invented their own thing, which is exactly how you get opensource projects to not support you.
