### ISSUE TITLE
Program Freezes at random times

### ISSUE THREAD

**Issue by BonitaTerror** [fireice-uk/xmr-stak#1675]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).
AMD RX 580

# Issue with the execution
  - Do you compiled the miner by our own?
  ```yes
  run `./xmr-stak --version-long` and add the output here
  ```Version: xmr-stak/2.4.3/26a5d65/master/lin/amd-cpu/aeon-cryptonight-monero/0

Execution has worked fine for quite some time. I had the program operating seven days straight and randomly in the middle of the night this week it stopped working and when I checked the pc in the morning the terminal had closed. I wrote it off as someone accidentally closing the terminal through the keyboard by luck. However I restarted the program and it worked for a few days until it happened again last night. I saw this morning and when I checked the terminal was opened and stopped on Result Accepted by pool. The cursor was blinking at the bottom of the terminal but I could type nothing. Not even Crtl+C would end the program so I had to close the terminal with the mouse. I tried running xmr-stak again like last time but now it is stuck at the part where it says:

 Compiling code and initializing GPUs. This will take a while...

it is taking a while now(ten minutes before I stopped it), but it never has taken more than a fraction of a second before, even with the same message being displayed before it connects to the pool and begins mining. 
I am pretty clueless at the moment and I realize it might not be an xmr issue but I don't really know where to start
Thank you

**Comment by Spudz76** [comment]
Seems heat or power related, what was the local environment like (hottest day in a week?)

**Comment by BonitaTerror** [comment]
It may be heat related, but not due to weather. The environment has been relatively the same. However, between the first and second time the problem happened I switched to using an aftermarket cooler. When I checked the temperatures after a while with the new coolers they seemed to be running around 20 C cooler. But I will try to make some adjustments and get back to you. Thanks again!

**Comment by Spudz76** [comment]
Fans/coolers can draw a couple amps on 12v rail, maybe the new air mover is a bit much for total watts on 12v for PSU?

If the new cooler is PWM/smart/thermostat controlled and not on 100% all the time, it may be a 12v dip for spin-up (can be 2x the spec/average draw).  If you have physical/spinning drive and it has power management/spindown enabled it could suck an extra 60W+ when it spins back up.  Inertia is a pain in the watts for DC motors (drives and fans).

Disable any drive parking, set fans at 100% (or some other reasonable fixed speed) to avoid major 12v rail watt changes.

Some PSU don't regulate very well and don't boost supply quickly enough at the top of their rating.  Some show more than one rail on the label, but are really single rail internally.  Single rail have more trouble making clean regulation since every device is on the same "pipe", and worse sensing of remote loads.

I run ProMiner 1000W PSU at about 700W total actual load and still have some problems with running power management (nvidia power limiting) due to that causing 12V rail ripples/dips which make stability bad.  I was rock stable without limiting power as hard, so I am nearly certain it's wattage ripple for me as well.

**Comment by BonitaTerror** [comment]
I think I might have found the cause of this problem is power surges. I noticed after it happened twice during the day while I was home. It has as of now been running smoothly for about 24 hours or more and no power surges have occurred in that time either. It explains the one time the machine was completely off but could it explain things behaving strangely even though the power wasn't cut completely? Also I would like to ask if there is a forum where things could be talked about in relation to xmr stak that might not be relevant to being an open issue on github (in case you guys predominantly want these to be possible code issues) thanks again

**Comment by Spudz76** [comment]
If the PSU has unstable input from AC line it will have trouble providing stable power on the DC side, and the highest draw (12V for GPUs) will usually suffer first.  Probably the GPUs crashing out save the rest of the motherboard from dipping volts too far so it stays running otherwise, other than the one time AC must have dipped out or surged too much and PSU shut down.

So it was PSU and dipping rails, but caused by unstable AC instead of heat or uneven DC loading.

**Comment by Spudz76** [comment]
Your other question, I'm not opposed to usage problems even if environmental being here.
I don't think there is a forum really other than possibly one of the mining subreddits but I haven't checked.  At least general miner app discussions happen over there, maybe not xmr-stak specific ones so much though.
