### ISSUE TITLE
Does support BitTube (ipbc) now PoW algorithm

### ISSUE THREAD

**Issue by eddiewang927** [fireice-uk/xmr-stak#1688]
Hi 

BitTube (ipbc) will hard fork on block 110,000 and switch to unique CN Saber algorithm
Does xmr-stak support  CN Saber?

Thanks

**Comment by Spudz76** [comment]
It's apparently a modified CN-Heavy so it should not be too difficult.

Looks like since they forked xmr-stak to make [their own miner](https://github.com/ipbc-dev/bittube-miner) (?) they should probably submit a pull request.  Coordinating with upstream is better than maintaining a lagged repository.

But until then, just use their miner, it would be very strange if it didn't support the hardfork.

**Comment by Spudz76** [comment]
Guess #1689 has arrived so mostly blah to what I said above

**Comment by psychocrypt** [comment]
Could someone please provide me with a pool for bittube2 and an wallet address.

**Comment by evgbog** [comment]
tube.ingest.cryptoknight.cc:5632

bxcyUo7SkbnPhkPyVj114qErnxJpyMweaDsDYXQLZA5mde8ei3EX4BMJf1dzTAmSZrjnpmaafZhEEczjNB1frWYh2jkRqL3cd

**Comment by Florigs** [comment]
hey @psychocrypt any news for pull #1688 and #1689 ???????

**Comment by psychocrypt** [comment]
I will have a look to it hopefully soon. We are currently under heavy
workload and it is summer ;-)

**Comment by psychocrypt** [comment]
I am currently working on this issue. I have CPU and AMD ready but NVIDIA is a little bit more difficulty because the changes in the algorithm looking more than less random.

**Comment by psychocrypt** [comment]
Could it be that the NVIDIA implementation of the bittube miner not work?

**Comment by Florigs** [comment]
very few mine CN heavy (and variants algos) with Nvidia? i think the integrated BitTube miner based on 2.0 of xmr stak supports AMD only?

**Comment by psychocrypt** [comment]
The bittube miner supports cpu and amd and nvidia via opencl. The bittube
miner is a fork of xmrstak. From the issues I can see that the devs have
trouble to implement the POW on Nvidia gpus. The reason is that on an
NVIDIA gpu 4 threads working together to solve one hash, the changes they
made introduced some ugly dependancies in the slowest part of the miner. I
think after I implement bittube2 for NVIDIA the hashrate for nvidia will
not the same as cryptonight heavy.

**Comment by Florigs** [comment]
@psychocrypt i think this is on purpose changes since BitTube wants to avoid FPGA's and botnets to be GPU friendly only. Again if you can already implement it on AMD already that would be a huge steps and competitor miners (i won't put the names here) have already implemented CN Saber and mining since the fork. At the moment BitTube is becoming the 3rd most important CN coin and taking more and more space so for a great miner as Stak it should be supported, all hiveos users like me are not able to mine Tube because of this. cheers.

**Comment by Spudz76** [comment]
Very soon Moore's law, and all this en-masse profit jumping with HiveOS/MultiMiner/etc will eliminate all this silliness about avoiding the future.

Electroneum already gave up and went back to original Monero format because GPU morons all left at the same time (all running same autojumpers, same coinprice feeds, so they jump at the same time), so they had no choice but to switch back and let ASIC back in to keep the network processing.  All other coins will follow this pattern, except Monero itself precisely because of existing botnets (that will just keep going because profit is always 100%).

Both things this coin fights hardest against will also kill it, as they are the only two ways to have any network stability and no delayed transactions, unless everyone abandons this profiteering idea.

The actual method to keep out ASIC/FPGA is to stop jumping coins for minor profit differences and support the network(s) of your favorite coin or two regardless if it pays less this week.  Unfortunately the "dumbass mode for profiteering" apps are getting really easy and more stable, and that is precisely what is going to kill coins.

A better way to control mining would be block any miner with over a GPU-capable hashrate, including proxies with too much hashrate.  You got work done too fast over the last hour, so it's not a luck run, bye.  ASIC/FPGA could still participate then but would have to throttle down to a fair GPU speed or get banned.  Level the playing field, don't dig trenches and destroy the field - that hurts both sides.

**Comment by psychocrypt** [comment]
implemented in #1717.
Can someone compile xmr-stak under windows and than test bittube with a NVIDIA GPU. I have currently no system with Nvidia GPU available. It should work but I like to test it before the release.

**Comment by Spudz76** [comment]
CUDA 8.0 works
Testing the rest too

**Comment by psychocrypt** [comment]
tested with nvidia on windows?

**Comment by Spudz76** [comment]
Yes, Win7 GTX970 latest drivers

CUDA 9.1 works (2H/s faster than 8.0)

**Comment by Spudz76** [comment]
CUDA 9.2 works, maybe 1H/s faster than 9.1

Ran all three builds on pool/wallet above, until I had at least one result.  CUDA 8.0 ran for 6 results none rejected.

**Comment by psychocrypt** [comment]
The latest release https://github.com/fireice-uk/xmr-stak/releases is now supporting bittube.
btw NVIDIA GPUs get an 5% since the last PR @Spudz76 tested.

**Comment by bfsazeni** [comment]
hallo, i use version xmr-stak-v2.4.6-cuda9.1 on SMOS. Pls help me what currency to use in settings. --currency cryptonight_ipbc doesnt work. Thanks a milion!

**Comment by psychocrypt** [comment]
if you like to miner bittube please use the currency bittube2 because the
POW algorithm has changed
