### ISSUE TITLE
new block fork electroneum

### ISSUE THREAD

**Issue by hassangetz** [fireice-uk/xmr-stak#1695]
how to setup xmr stak after the latest block update

**Comment by psychocrypt** [comment]
If I remember correct we have not updated xmr-stak so it should still use
cryptonight. If not you can select cryptonight as currency

**Comment by Spudz76** [comment]
Yeah all they are doing is jumping back to the ASIC-exploited old normal cryptonight so select `cryptonight` as currency

This is because all the auto-profit GPU miners were being selfish and not running 24/7 so nobody was around to process transactions sometimes (when prices sucked).  So their new policy is: ASICs welcome back, go ahead and destroy the GPU miners since they refused to show up for work.

Haha labor disputes basically.

But yeah xmr-stak never removed the old algorithm, just switch back to it by generic name and DO NOT use `electroneum` as currency as it is still mapped to v7 or whatever.

**Comment by Terlin** [comment]
Ignore earlier post, found currency in pools.txt.
I still thought it was in config.txt :)
