### ISSUE TITLE
xmr-stak-win64 release 2.4.5 inital setup does not complete. CPU.txt file not created

### ISSUE THREAD

**Issue by asbradford** [fireice-uk/xmr-stak#1714]
Please provide as much as possible information to reproduce the issue.

*I have downloaded xmr-stak-win64 release 2.4.5*
*When I run the xmr-stak.exe I select "Run as administrator"*
*Initial auto set-up does not complete.*
*cpu.txt file is not generated.*

*I previously had release 2.4.3 installed and working.*
*I have tried re-installing that release however the set-up also "stalls" at the same place.*

![untitled](https://user-images.githubusercontent.com/41141995/42632174-495d10a0-85d4-11e8-8f9b-dbb378bf27c5.png)

# Basic information
  - Intel Core i7-4790 CPU @ 3.60 GHz
  - Type of the GPU (if you try to miner with the GPU)  - N/A

# Compile issues
  - Windows 7 Professional
  - N/A

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  N/A
  ```

# AMD OpenCl issue

  ```
  N/A
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by Spudz76** [comment]
Try with `--noUAC` and if that works, disable UAC prompts completely (always allow / no prompts).

I do not know what happens with any of that stuff enabled, it's part of installing Windows7 to shut off everything that ever makes problems (UAC, SFP, Rollbacks, all get in the way more than help)

**Comment by asbradford** [comment]
Thanks for the suggestion @Spudz76 unfortunately it didn't resolve the problem.

**Comment by Spudz76** [comment]
OK then next idea, if you have the Intel iGPU drivers installed then run with `--noAMD` to make sure it doesn't probe OpenCL (Intel is very broken and crashes/hangs this miner).

If you were trying to use and actual AMD then remove the Intel driver, or locate its opencl dll and eradicate.

The full set of `--noAMD --noNVIDIA` is how to properly run a true CPU-only miner.  Otherwise it still checks what's available, loads OpenCL to probe things, loads CUDA etc (or attempts to).

**Comment by styxschip** [comment]
This may be related to anti-virus software. Are you sure you have turned off anti-virus software? I also encountered the same problem, I installed Kaspersky, although it has been added to the exclusion project, there is still a problem. Until Kaspersky is completely uninstalled.

**Comment by Spudz76** [comment]
@asbradford any luck????? we're dying of suspense.

**Comment by asbradford** [comment]
Huh, sorry for the late response @Spudz76  @styxschip ...   I've tried --noAMD --noNVIDIA but no luck (with UAC prompts disabled). I also attempted --cpu FILE   however it still hung at "Elevating due to ...". 

My next effort will be to either uninstall Kapersky  or add the miner to the exclusions. What would be strange, if that is successful, is that when I previously had the miner installed to worked absolutely fine with Kaspersky running.

**Comment by Spudz76** [comment]
Wouldn't be the first time a definitions update nuked another version.  I bet its blocking the opencl backend dll from loading, regardless of the directory whitelist (which only applies to exe? maybe?).  Would not put that past idiot antivirus programmer logic.

ESET works good still, honors exclusions for real (with subdirectories, with dll and all other file types included).

**Comment by Spudz76** [comment]
Ok, so in [their docs](https://support.kaspersky.com/11444) it looks like not only do you have to add the directory to the scan whitelist but you also have to mark the application as "Trusted" somewhere separate, in order to get it to quit being intrusive completely.

Being in "Trusted" does not exclude it from scanning.
Being in "Whitelist" does not exclude it from runtime weird actions blocking.
So both need to be defined for complete ignorance?

**Comment by Schmoozer0069** [comment]
I had to shit can Kaspersky, too many issues with it ignoring white lists.  I cannot tell you how many times I have had to redownload XMR Stak because it deleted the .exe

The workaround I used until I switched to bitdefender was to shut off Kaspereky and anything related to Kaspersky while I was mining.  Another thing to think about is whether Microsoft Defender is causing some of your problems.  I spent several hours unfucking that shittastic design.

**Comment by asbradford** [comment]
Thanks @Spudz76 for the link... talk about needlessly over complicating something. I'll certainly give it a crack.

@Schmoozer0069 I have doubled checked and Defender is turned off. 

Still, not wanting to be defeated, I have successfully compiled the miner for macOS on my old macbook. It works... the hash rate is underwhelming as you might expect but it feels like a small victory for now.
