### ISSUE TITLE
[Request] Different Algorithms for fallback pools

### ISSUE THREAD

**Issue by DarrenRainey** [fireice-uk/xmr-stak#1716]
Hello could you add a feature that allows the user to set multiple different algos for fallback pools

e.g
pool-1 monero.example.com - Monerov7
pool-2 aeon.example.com - cryptonight_aeon

**Comment by Spudz76** [comment]
This has been requested several times, there are some functional/design reasons that make it very tough, near rewrite level work to support it properly.

To switch while running would be almost like exiting and starting over as far as differing memory requirements (some coins are lite 1M, normal 2M, or heavy 4M per block).

This is why there is no donation when you use a weird coin, we can't switch algos only pool connection point.

Use a multiminer supervising app / cronjob?  That could detect the xmr-stak setup for monerov7 has choked and lost rate, and kill it and run the other complete xmr-stak setup for cryptonight_aeon.  Not sure how to detect when the primary pool is working again if it connects but then has problems, though, so fallback may be difficult or manual.

**Comment by DarrenRainey** [comment]
Ok I was looking at the source code a few weeks ago. I'm not 100% familiar with the code base but I guess the best option would be to make an management program like you said and maybe either use the built in http api or modify the program to directly interact with the management program.

**Comment by Spudz76** [comment]
Yes it would assist many projects to add a control and config interface to the JSON API.

The second most requested things besides new/updated coins are new command line options mostly nobody would use by hand, and belong in an API instead, because frontend control apps are using them.  That makes the usage docs for command line sort of `TL;DR` for the average user hoping for simplicity.

Also once there is an API one could actually `stak` a bunch of miner worker endpoints and run them from a main `xmr-stak` instance more like a dashboard. It really shouldn't matter if the miner device is in the local computer, and would provide the similar but more robust function as a proxy to combine a bunch of low rate CPUs into one jobbing group.

Big downside and likely why there isn't one yet, is as soon as you add writable API every hacker anywhere will try to break it so implementation should be very careful.  Script kiddies would be hunting for ill-configured miner APIs and constantly attempt to hijack workers, etc if it were too public and open (if end user wants to map to outside port, that's on them and at their Internet device/router or VPN or SSH tunnel or etc).

**Comment by DarrenRainey** [comment]
Yeah there are projects like xmrig-proxy that allow you to just setup most of the stuff server side but the main problem is having the miner use the right algo not sure if its possible to have xmr-stak detect what algo the server proxy uses but I'll look into it later.
