### ISSUE TITLE
AMD Vega64 Cards Work When They Feel Like It

### ISSUE THREAD

**Issue by BonitaTerror** [fireice-uk/xmr-stak#1790]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU. Intel i3
  - Type of the GPU (if you try to miner with the GPU). 4 Vega64

# Issue with the execution
  - Do you compiled the miner by our own?
  ```no```
  run `./xmr-stak --version-long` and add the output here
  ```Version: xmr-stak/2.4.7/c5f0505d/master/win/nvidia-amd-cpu/20```

# Stability issue
  - Is the CPU or GPU overclocked? No
  - Is the Main memory of the CPU or GPU undervolted? No

I seem to be having problems with my mining rig randomly shutting down (the software not the whole computer) for the time being I have attributed this to it most likely being an issue with temperature because this didn't happen anywhere near as frequently when I was using 3 AMD cards. I have changed no settings when adding the fourth, and I am almost certain that I have enough ram and watts from my power supplies. However, when these recent crashed happen, I begin getting issues that a device of index 'y' cannot be found(it seems to be a random different card each time). The only way I can seem to fix the problem is by restarting the computer a random number of times(sometimes too many times). If this is how it has to be, I am okay with that, however because I am changing nothing and sometimes it works and sometimes it refuses to, I would really like to understand the possible underlying causes of this. Could it be due to Windows being unstable in these conditions, not allotting enough ram to my gpus in the bios, amd drivers not being stable, etc. I am really just hoping to get a better understanding of this rather than restarting it a bunch of times aimlessly

Otherwise I just feel like this:
![capture](https://user-images.githubusercontent.com/39413300/44176844-71984a80-a0b9-11e8-964c-5dc2ef70900e.PNG)

**Comment by Spudz76** [comment]
Definitely power related.  I had to rip the modular connectors off my PSU and solder them direct to the rails before I got stability, it had nothing to do with the software.  Modular whips can not handle the amps, get hot, then fail.  I would imagine you'll find them lightly cooked or partly melted (at the PSU end).

Also the best slot extensions have the old normal 4-pin Molex, run maximum two slots per PSU whip, avoid the SATA-to-anything adapters unless it's just one slot per whip, even then iffy.  However I also have reasonable luck with the PCIe 6pin slot boards but I hook them direct to a PCIe whip (no SATA adapter).  I seriously have a box full of the SATA adapters, they only cause problems, SATA is not designed to support 60-80W, more like 45W.  Any wire less than 16ga might as well be a resistor, watch out for PSU with cheater wires, thickened coating so they look like 16ga but are really 20ga inside.  They get away with it on normal duty cycles but once you try 100% hard work they melt down.

**Comment by BonitaTerror** [comment]
Wow, thank you that's not at all what I would have thought. The risers I have right now are powered through sata to 6 pin pcie power. Just to make sure o understand what you've said, it would be best for me to directly power the risers pcie to the psu, rather than connecting it through a sata adapter or even molex?

**Comment by Spudz76** [comment]
Yes, if you have enough PCIe to just go to the slottys direct (and the GPU of course) it is much better off.  Or some Molex to PCIe but they have to be good thick wire (12ga or 14ga, but 16 should work).  It tends to be tough to find single Molex to PCIe though since when you use them on a GPU (not a slotty) it could pull 160W for which you need two Molex feeding one PCIe.

The weak bit about SATA power is how they are fingers laying on fingers (single face contact).  Just not enough surface area for the power needed.  They work fine for 80W to spin up some old drive though, but that is for a few seconds, not hours/mining.  As things get warm they also lose conductivity so it spirals out as well.  Some older Hawaii cards have been known to melt the SATA part right off, but they tended to be heavy load on the slot (motherboard toasters!) with triple fans and such

The square pin type are OK but not on the small/micro pins, where I would call the PCIe pins 'normal' size for the amps.  Some square pin connectors only contact on two faces of the pin, though...

Thus the old round 4-pin molex actually have the best surface contact and being circular seem to also grip better than square, "hugs" instead of a few faces touching.  You do have to twiddle with them and make sure each of the four seated well, with some of the looser ones sometimes.

The limit of about two slotties per whip is so the PSU end (if modular) doesn't melt.  I had run three-per for a while but then got unstable and was pulling out hair, until I checked the modulars @ PSU and noticed warped plastic and even melting coatings for the first couple MM.

**Comment by BonitaTerror** [comment]
I changed all my risers to be powered by pcie. It definitely seems more stable having done that, but I am still getting strange crashes and restart issues. Is there anything else I should look into as well?

**Comment by BonitaTerror** [comment]
I actually may have spoken too soon. It appears that I can't seem to run my rig for more than 10 minutes without it crashing now. To give more information the entire system seems to hang. I still get a display on my monitor but nothing updates (mouse movement, blinking cursor in the terminal etc). I've been looking into other potential causes but wanted to see what the general advice was here first. I would be surprised if the direct PCIe power is causing more instability than the SATA adapters I was using earlier based on what you said. Although I am scratching my head because I haven't changed anything else in my system. I've been told that it's possible my machine doesn't have enough combined ram/virtual memory. However since it hasn't even been this unstable I don't believe it could be the cause of this recent case of horrible stability. One thing I hope isn't related is the high number of power outages in my home recently. My rig is plugged into a surge protector but I wonder if it is possible that something has taken damage from these outages and is no longer stable. However in typical use (that I have recently employed for testing purposes) the stability of the machine is nothing to worry about

**Comment by Simaex** [comment]
@BonitaTerror it still feel like power problem. Try to rule it off by removing all cards but one and check for stability. If all's Ok add cards one at a time and repeat stability test. You problem may be caused by overheating of some PSU parts. Before you bad connectors  prevented overload of PSU. Also check you power consumption at the wall. If it exeeds 90% of nominal PSU power rating you can have issues.

**Comment by Spudz76** [comment]
Definitely PSU, not ram or swap.

I was unable to get stable on the rig that melted the plugs at the PSU at any time, even one slot per whip, once the connector is charred it is also really bad at its job (conducting).  Thus my cut and solder bypass.

**Comment by BonitaTerror** [comment]
I actually found out the cards were undervolted as well. I thought I had changed that. Now they are completely default as of last Saturday and I have had the 3 running stable since!
