### ISSUE TITLE
Change donate wallet

### ISSUE THREAD

**Issue by mPak2018** [fireice-uk/xmr-stak#1814]
There was a need to change the wallet to which the donat is going.

Who can tell where in the code to change the wallet to which the donat is going?

**Comment by psychocrypt** [comment]
Why do you need to change the donation wallet address?
There is no hard coded wallet address in the code.

**Comment by fireice-uk** [comment]
Sorry mate, we get a smartass like you trying to do a knock-off of xmr-stak while redirecting donate to his own account every week. Smarter guys package a keylogger or wallet stealer too since modern AVs are too dumb to have a setting where you can say "I'm OK with miners but not OK with keyloggers."

**Comment by psychocrypt** [comment]
xmr-stak is GPL even if you provide someone with an binary you must ship the full source code with all changes. This means the customers can change your hard coded donation any time.
