### ISSUE TITLE
Working guilde of installing On Ubuntu with AMD?

### ISSUE THREAD

**Issue by MikhailKlemin** [fireice-uk/xmr-stak#1835]
Unfortunately the Linux instructions here are not correct. The AMDAPPSDK dropbox link is broken and it is not possible to get from other places. 

The AMDGPUPRO driver which is available from AMD site, installs but that only gives errors OPENCL during compilation of xmr-stak, or if I somehow make it compile then it do not see the cards. 

The only way to install is to jump over millions of threads suggesting this and that, but I could not make it work.  

So if there anyone who can write down reproducible steps on installing xmr-stak on fresh Ubuntu 16/18 with AMD video card?

**Comment by Spudz76** [comment]
Ubuntu 16.04.5 server installer, this will put you on kernel 4.4.0 series which works nicely.

Find amdgpu-pro-17.50-552542.tar.xz and install it with legacy headless.

Purge all bad default OpenCL headers with `sudo apt purge opencl-headers*` and double check there is no `/usr/include/CL` at all

Download OpenCL headers [directly from Khronos](https://github.com/KhronosGroup/OpenCL-Headers/archive/master.zip), unzip, move the resulting `CL` subfolder to `/usr/include` (as root of course)

Add `-DOpenCL_LIBRARY=/opt/amdgpu-pro/lib/x86_64-linux-gnu/libOpenCL.so.1` to the cmake command otherwise it will probably locate the wrong library

It should find everything and build fine, and run fine.  The old SDK is no longer needed and AMD themselves (as much as they ever agree on anything) say to use these official Khronos unified headers in all cases, and the library comes with the driver and can be linked to just fine (no need for the SDK library either, which was always true - we only had the SDK step to get the headers really).

In all cases the system headers don't work with the proprietary AMD stuff, it is for the open source Mesa/Clover stuff (if they even work with that?).

And this doesn't work yet with 18.x drivers (18.10 allegedly might work) but fixes are being worked on.  It will appear to mine but will never produce valid results.

**Comment by MikhailKlemin** [comment]
That worked out, thank you very much!
