### ISSUE TITLE
CUDA 10/RTX 20XX support.

### ISSUE THREAD

**Issue by OhGodADog** [fireice-uk/xmr-stak#1854]
Hello,

Looking at the CMakeLists.txt, there doesn't seem to be any specific compile options for CUDA 10 yet (DCUDA_ARCH=75 for example). 

Upon compiling on Ubuntu 18, with CUDA 10 installed, doesn't throw an error, but no idea how it will perform with the RTX cards. 

I want to know, if compiling with no -DCUDA_ARCH, would allow support and best performance for multiple generations of cards (Pascal/Volta/Turing), especially, with no specific support out for Turing yet.

**Comment by psychocrypt** [comment]
you can always select a architecture with cmake by hand. never the less the
pr is already on my disk. as soon as I have a fee minutes I will pish it.

**Comment by Spudz76** [comment]
Ironically was just working on this too

FindCUDA.cmake plugin has reference to it (in cmake 3.12)
It also says don't use itself anymore and after 3.8 `enable_language(CUDA)` works and you just dump `.cu` files in with normal methods (not the cuda_add_library` and aliases from the old plugin.  Unclear if that works on Windows...

**Comment by xbkingx** [comment]
Just a note that CUDA 10.0 prevents compiling on Windows 10 in VS2017. Same CMake error as early VS2017 with CUDA 9 ~6 months back: xmrstak_cuda_backend_generated_cuda_core.cu.obj.Release.cmake:219.

For those wanting temporary fixes:


The Easy Way:
&nbsp;&nbsp;Use the workaround they already had for 9.1 and 9.2 in the CMakeLists.txt file.
&nbsp;&nbsp;Change line 189 from this:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`(CUDA_VERSION VERSION_EQUAL 9.0 OR CUDA_VERSION VERSION_EQUAL 9.1 OR CUDA_VERSION VERSION_EQUAL 9.2)`
&nbsp;&nbsp;to this:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`(CUDA_VERSION VERSION_EQUAL 9.0 OR CUDA_VERSION VERSION_EQUAL 9.1 OR CUDA_VERSION VERSION_EQUAL 9.2 OR CUDA_VERSION VERSION_EQUAL 10.0)`


<sub>The Hard/Bad Way: 
&nbsp;&nbsp;Revert to CUDA 9.2 by changing your environment variables (affects all things CUDA)
&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;- Install CUDA 9.2 (hopefully you didn't uninstall it before testing)
&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;- Change your CUDA_PATH to point at the v9.2 directory (just search for environment variables in Start and CUDA_PATH in the lower pane of the control panel)
&nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;- Close all consoles and instances of VS2017, delete the build folder, and try again.
&nbsp;&nbsp;If that doesn't work, go back the the environment variables and look for any mentions of CUDA (it will be in your User PATH and the System PATH), and change the order so that v9.2 is above v10.0. Now insert coin and try again.</sub>

Windows 10 x64 (10.0.17134 Build 17134)  /  VS2017 (15.8.5)  /  NVidia drivers 411.70  /  CUDA 10.0/9.2/7.0  /  CMake 3.12.2

**Comment by psychocrypt** [comment]
Thanks for the information. I will extent this cmake guard to support cuda
10.

**Comment by psychocrypt** [comment]
cuda 10 support added in #1857
