### ISSUE TITLE
Fermi support

### ISSUE THREAD

**Issue by Boynk** [fireice-uk/xmr-stak#1960]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - Type of the CPU.
  - Type of the GPU (if you try to miner with the GPU).

# Compile issues
  - Which OS do you use?
  ```
  add **all** commands you used and the **full** compile output here
  ```
  ```
  run `cmake -LA .` in the build folder and add the output here
  ```

# Issue with the execution
  - Do you compiled the miner by our own?
  ```
  run `./xmr-stak --version-long` and add the output here
  ```

# AMD OpenCl issue

  ```
  run `clinfo` and add the output here
  ```

# Stability issue
  - Is the CPU or GPU overclocked?
  - Is the Main memory of the CPU or GPU undervolted?

**Comment by Boynk** [comment]
Please, please add it.

**Comment by liam-b** [comment]
I have used xmr-stack with Fermi before (GTX 680 I believe) and from what I can tell it is still supported, you will just have to build it yourself from source.

(From the latest release notes)
> We dropped NVIDIA Fermi support in the precompiled Windows binaries

**Comment by Spudz76** [comment]
Build with CUDA8 like it's 2 years ago (where your GPU came from)

**Comment by Boynk** [comment]
Yes that works, thank you. Suffering a 50% drop in hash rate though. Is that normal considering the changes v8 vs v7 ?

**Comment by Spudz76** [comment]
Regenerate `nvidia.txt` using currency set to a v8 type it will balance differently than old configs based on v7.

Also I have personally seen better hashrate using `xmr-stak --noNVIDIA --openCLVendor NVIDIA` and using the OpenCL path instead of CUDA, so try that as well (and possibly retune the `amd.txt` then to improve over autodetections)

**Comment by Spudz76** [comment]
I have not recently tested on my other old GTX495/550 rig since it was unprofitable even with v7 it had been shut off for 2 months.  Might fire it up and just check it out though for curiosity.  My electric rates are sort of above average though.  Run the laptop just for kicks now and then, it is likely non profit also.

**Comment by psychocrypt** [comment]
50% drop in hashrate for old nvidia gpus is mormal :-(

**Comment by Boynk** [comment]
Thank you all for feedback. I will have to suck it up and update my hardware.
