### ISSUE TITLE
Illiminating Virus Detection on all Things XM*

### ISSUE THREAD

**Issue by paulbrasted** [fireice-uk/xmr-stak#1997]
First of all  thank you for all the work done with regards to the latest Menero fork!
...
The xmr-stak miner , xmrig  and xmrig-proxy all get recognized as a virus. I have downloaded the source for these and would like to have a go at editing the source to bypass this detection. I am not familiar with virus software detection methods but am a lifetime programmer and  am up for the challenge. Does the team think this is possible and if so could you give any direction.

**Comment by psychocrypt** [comment]
It is not possible. The AV softeware is detecting the code signatures from
the cryptonight algorithm. Due to some bad guys we need to with the false
positive.

**Comment by uvtzxpm** [comment]
Many of the people who use antivirus software would be annoyed if their software did _not_ detect the sneaky crypto miner (that they didn't install) sitting in the background, eating their CPU/GPU and making their computer slow.

So, it's not a good idea try to get around the "false positive". Many users simply consider miners to be a "virus".

**Comment by Spudz76** [comment]
You should use "programming since <year>" or "for <actual_number> of years" since by what you've said and (mis)typed you must be about 18 and maybe coding for 4 years.  Also based on every lifetime being different, it is a pointer with no sizeof()

I have a lifetime of programming too.  But I have been programming since 1988, and have also been a proofreader/editor (perhaps the most indirectly applicable skill to code nobody considers).  Accuracy and if not possible, consistency, is above all else.  Without that, your code will not have forethought or any 'rules' and will look like you've not even read over it a second time, let alone a third or fourth.

That being said I normally just say "been programming for decades" once I had gotten over 20 years.  It goes over slightly better than "been programming since before you were even born"

**Comment by psychocrypt** [comment]
this can not solved by us :-(
