### ISSUE TITLE
Feature req: Detecting the valid share present

### ISSUE THREAD

**Issue by qxxrbull** [fireice-uk/xmr-stak#1999]
Some of users didn't use the correctly AMD driver version , that cause the share which submit to pool are all invalid.
I think we can add a feature that can detecting the share valid present , which lets user to know if the share are all invalid should adjusting something (like driver verison or intensity ... etc).

**Comment by Spudz76** [comment]
If a tree falls and nobody is looking, did it have termites?
Trees should send us notifications before they fall on us or our belongings.

How about pay attention, and it does detect and logs those problems to the Results Report.  What else should it do, freak out and play loud music?  Go on strike?  Send emails?  Become sentient and solve its own problems?

This is a feature for an outside observer (monitor/management software).  You would not have the arsonist also watching for fires, that is not safe or logical.  Also most pools will email you incessantly whenever anything feels slightly wrong, why add yet another thing that is going to do the same thing (cry wolf effect is far too real)

**Comment by psychocrypt** [comment]
This is something which can not solved really by  the miner. The problem is some broken driver create code which has race conditions in. The nature of a race condition is that you can have luck and it take many shares until the first invalid share is created. The miner itself can not decide if the driver is broken. You can define a threshold but who knows if this is correct.
We added since 2.5.0 the output of invalid shares to the log file. You can use grep or an external tool to monitor the actions.
Note: Invalid shares will not send to the pool. The are detected by the miner and will be ignored (but you see it in the log).
To test you miner the best way is to use a testnet pool like killallasics.moneroworld.com/ which has a very low difficulty  which helps a lot to test the miner. As soon as you have the right driver version you should never get invalid shares if you have not overclocked your GPU memory to much.
