### ISSUE TITLE
Confusion surrounding whether to choose currency "monero" or native algo "cryptonight_v8"

### ISSUE THREAD

**Issue by RinceWind84** [fireice-uk/xmr-stak#2017]
This is merely a suggestion.

I have noticed that many people don't seem to understand the difference between the two "currency" choices monero and cryptonight_v8

as I understand, monero is block-height dependent and hence will only work for xmr mining, while cryptonight_v8 will work for any coin utilizing the new pow-algo, including monero

as obvious as this may seem, a lot of people are getting it wrong and on MRR many rig owners are being forced to refund entire rentals because they have set their rigs to monero and rents them out as crytonight_v8. I have tried to shout about this to make people understand, but it hasn't proved very effective.

my suggestion: make it crystal clear in the readme.md that "monero" was meant for people mining during the hardfork. and that it will not work for any other coin/chain

**Comment by psychocrypt** [comment]
I understand you. But if someone is selection monero to mine e.g. graft
something is wrong on the user side. The problem is that most users do not
read the documentation and try something to hope it work.
If you have a wording in mind please feel free to provide a pull request
against the dev branch.

There is also mentioned that if a coin is not listed the algorithm must be
selected: https://github.com/fireice-uk/xmr-stak#supported-altcoins

**Comment by RinceWind84** [comment]
I think you are right. And personally I did not have a problem understanding the instructions.

What happens on MRR is that rig owner controls some settings and renter inputs stratum url, username and password. Since I also mine and happen to know how xmr-stak is set up, I was a able to clarify this to a bunch of people.

But yes, definitely user error. And one could argue that if you rent out a mining rig, the least you could do is try and understand how to setup your mining software. I guess I'll just leave it.

**Comment by Spudz76** [comment]
I am running on MoneroOcean which switches (allegedly) and using `monero` as currency.  I have `xmr-node-proxy` in between and it shows CN2v2 since the fork and has not switched (but it is also dual-wield-capable and configured as such)

Switching is not block height based, it uses the packet version from the pool job packet.  So if you run `monero` it should be functionally equivalent to the nonexistent `cryptonight_auto`, just like a multiminer system would want.  It will switch back and forth, since it does not care what the block height is.

**Comment by RinceWind84** [comment]
I am unsure if we are talking about the same thing. I may be wrong by calling it "block-height" dependent.

Here is my quick test of a LTHN pool. LTHN is running CNv2, or cryptonight_v8 as xmr-stak tends to call it.
![cngood](https://user-images.githubusercontent.com/37146335/47587783-52912100-d964-11e8-80a8-31a8e417ac22.JPG)
![cnbad](https://user-images.githubusercontent.com/37146335/47587784-5329b780-d964-11e8-8c2a-6d69e5ed69ee.JPG)

As you can see. setting "currency" to monero results in rejects. and cryptonight_v8 results in accepted shares.

The same test done on a xmr-pool will result in accepted shares in both scenario's

**Comment by psychocrypt** [comment]
The switch is only working with monero if the old block version is 7 and
the new is 8. It is not a algorithm detection included. This means if this
pool is not using block version 7 and 8 it will not work

**Comment by RinceWind84** [comment]
pool is using CNv2 , same as monero has switched to just recently.

and this was my point exactly. setting currency to "monero" will not work on coins that are not monero.

LTHN, CALIBER, Wownero etc.

**Comment by RinceWind84** [comment]
while setting it to cryponight_v8 will work on anything, since we have passed the fork.

**Comment by psychocrypt** [comment]
Ohh yes thats true. The currency monero supports only the monero fork all
other currencies will not be compatible.

**Comment by RinceWind84** [comment]
I am glad that we agree! Also I did not have problem understanding this myself, bu have come across several people who did. And hence my suggestion. But still I agree that people should probably just pay more attention to what they are doing ;)

**Comment by psychocrypt** [comment]
with the next fork we will be more clear in the release notes. I think the
devs of the coins can also help and provide information how the coin can be
mined to avoid wrong informarion coming up

**Comment by RinceWind84** [comment]
I am beginning to think that this a very local issue for rental services like MRR. since the rig owner does not know where his rig is pointed, for safety ofc.
Normal users would quickly be able to pin-point the issue and solve it

**Comment by Spudz76** [comment]
I suppose, but I was also basing my opinion on previous/old Issues here (+9mo old or so) where some multiminer control software wanted better switching features (via API) and that was more or less ignored or wontfix'ed due to complexity.  But if things are stacking up pointing to reasons for being more agile in the core so multi-same-time-mining is possible... why not?

Personally think there should be a network-drone "backend" so you could actually "stak" your "xmr-staks" (like proxy but alongside other local real devices, merged mining for the whole trellis, master xmr-stak connects to pool and the drones connect to the master-instance xmr-stak... etc)  The same drone-api would be what a multiminer control software would use, and requested previously.  Hot reconfig while running basically (some asked for file monitor/poll to check and reload config files while running, for same but much less efficient effect)

**Comment by Spudz76** [comment]
Then again once you open drone mode, hackers will flood in trying to intercept peoples mining drones into their own master tree (hijacks)... which is probably a piece of why not
