### ISSUE TITLE
Released xmr-stak-win64-2.5.2.zip contains missing/new files

### ISSUE THREAD

**Issue by BKdilse** [fireice-uk/xmr-stak#2022]
Extracted the zip, and it contains these 2 DLL files:

```
libcrypto-1_1-x64.dll
libssl-1_1-x64.dll

```
but missing these 2 DLL files (as per previous versions):

```
libeay32.dll
ssleay32.dll

```

Is this an error, or should they be renamed, or is it new.  They are newer versions?

**Comment by BKdilse** [comment]
OK thanks, sorry, didn't even read that, assumed they would be the same.

**Comment by psychocrypt** [comment]
You can use the latest release of the dep package (v3). v3 is not
compatible with v140

**Comment by BKdilse** [comment]
Thanks again.

**Comment by Spudz76** [comment]
I have been getting the win32 (for 64 though, confusing isn't it?) packages from:
[https://slproweb.com/products/Win32OpenSSL.html](https://slproweb.com/products/Win32OpenSSL.html)
People say the Lite one works, I have only used the full pack (for 64 bit).

[https://www.open-mpi.org/software/hwloc/v2.0/](https://www.open-mpi.org/software/hwloc/v2.0/)
version 2.0 works fine though app still written/compatible with v1.x again 64-bit version only (it is in the package along with 32 you'll have to unpack and grab the 64-bit headers and libs and dlls)

[https://www.gnu.org/software/libmicrohttpd/](https://www.gnu.org/software/libmicrohttpd/)
and this "win32" also has 64-bit included

once you have these unpacked and either system installed (openssl does this nicely) or pointed to with `CMAKE_PREFIX_PATH` similar to pointing to the old deps tree... it should all work.  You will need to ship the hwloc dll from the zip with the resulting `xmr-stak.exe` however since that pack does not support static link like the original packs.

**Comment by Spudz76** [comment]
^^ and those new openssl dlls are how they are named in the OpenSSL official pack, versus the older short names

I guess the release is built against the above linked OpenSSL build now, or similar.

**Comment by Spudz76** [comment]
Cool, haha, I didn't even notice that was released.  I quit using the v2 pack long ago and quit checking the release page since then

**Comment by BKdilse** [comment]
Lol. I didn't even see it until psychocrypt mentioned it, then I looked again.

**Comment by psychocrypt** [comment]
Yes I have currently not updated the documentation. Only the release notes
point to the new dependency package.

**Comment by BKdilse** [comment]
Yeah, that's what I read, so thought you hadn't had the time, understandable :)
