### ISSUE TITLE
PC Lags Badly Even When Not Using CPU to  Mine

### ISSUE THREAD

**Issue by Klinkers** [fireice-uk/xmr-stak#2027]
Please provide as much as possible information to reproduce the issue.

# Basic information
  - i7 - 6700k
  - ASUS ROG STRIX 1070
  - Windows 10 x64 Build 1809

# Stability issue
  - Nothing is Overclocked or changed from Factory standard
  
The PC Lags badly even with --noCPU when using 2.4.x i never got any lag even when using 3 out of the 4 cores (6 of 8 threads)
if there is any other details you need please feel free to ask.

[cpu.txt](https://github.com/fireice-uk/xmr-stak/files/2522748/cpu.txt)
[nvidia.txt](https://github.com/fireice-uk/xmr-stak/files/2522749/nvidia.txt)

**Comment by Klinkers** [comment]
thanks this solved it. but dont know why it would cause problems with screen as i have 2 x 1070 and am only mining in one and using the other for my screen. but either way that worked and solved the problem. Thanks

**Comment by Spudz76** [comment]
Be sure you are actually running on the GPU you think you are...

CUDA will sort the index as `FASTEST_FIRST` by default not by slot number (like normal APIs, and even the `nvidia-smi` tool)

set system global environment var: `CUDA_DEVICE_ORDER=PCI_BUS_ID` so that CUDA index and actual slot (thus `nvidia-smi`) always match up.  Otherwise it might have decided your primary should be fastest (based on x16 slot, or other things) and put it in index 0 even though the other one is index 0 in `nvidia-smi`
