### ISSUE TITLE
Can you add a new algo?

### ISSUE THREAD

**Issue by Cideg** [fireice-uk/xmr-stak#2043]
Please add the algo: CN-Heavy-Fast
http://207.180.227.127/
Many thx

**Comment by psychocrypt** [comment]
what is cn-heavy fast please add links ro the description and coin which
using the algo

**Comment by ClashLuke** [comment]
CN-Heavy-Fast is an algorithm which focuses less on GPU resistance and a lot more on ASIC resistance. It allows users to get approximately x5 the hashrate they would get in CN (normal). This is done by reducing the number of iterations from two to the power of nineteen (2^19) to two to the power of twelve (2^12).
As of right now, the only coin using this algorithm is bitstream, which has to use a fast halshing algorithm which also uses a big scratchpad. Hence the creation of Cryptonight-Heavy-Fast.
Since the only alternation is the number of iterations, the variations of cryptonight (v1, from monero v7; v2 from monero v8) can still be implemented in CN-Heavy-Fast.
A link to bitstreams github (for reference) is here
https://github.com/BitStream-Project/BitStream

**Comment by Cideg** [comment]
> Please add the algo: CN-Heavy-Fast
> http://207.180.227.127/
> Many thx

**Comment by psychocrypt** [comment]
please provide a link to a pool. we reqired a minimal hashrate. For that
algo the coin should have more than 30MH/s

**Comment by Spudz76** [comment]
Network Hash Rate: 280.73 H/sec

So there is one cpu on the network?  Super popular.

**Comment by Cideg** [comment]
LOL then compile the GPU miner and off you go :-)

**Comment by ClashLuke** [comment]
Excuse me, but what the **** are you doing in here? It doesnt matter how popular a coin is or how popular its algorithm is. The only thing that should matter is, if the technology is interesting or not.
The thing you just did is like kicking those who do ACTUAL development of any kind right in the balls.

If you want it to be like that, let it be, but I can tell you, that the community will turn their heads away from people like you.

Good day.

**Comment by Spudz76** [comment]
xmr-stak has had a minimum hashrate policy before bothering to add new currencies, since forever.  Sometimes the number changes but you were given the current expectation above.
Take it more as a goal, and less as a bouncer bullying you.

Nobody has time to bandwagon on coins that most likely will be worthless, or introduce bugs into existing logic just to support a coin that ends up mostly vaporware.  Also donation would not work as there is no "club accountant" to track 80 currency wallets and exchanges and whatever (new coins can't be converted for quite a while / if ever... another huge problem)

Unless of course *you* have time to add it yourself and submit a proper PR.  Especially since it's so easy (apparently).  However we also do not clean up code, as then we might as well just write it, so it must match formatting and style as already exists in the file - ready to publish or as close as possible.

On occasion oddball small coins got added, but because their creators submitted their own patches (aka did all the work to support their own currency).  Many do it the wrong way and fork a miner while breaking the upstream linkage and then hack it (usually badly) to support their bad idea, so even if someone had spare time to merge code they broke the linkage so diffing is much, much, much more difficult.  Also a code license violation... in most cases

However all bugs introduced by something are the responsibility of whomever authored the garbage code, including forks and any other updates or fixes.  Many times that part is where the ball gets dropped.  Which defers maintenance to core devs with scarce spare time.  If you think people get mad for refusing to add a currency, imagine when we drop a currency later on because nobody wants to keep it updated and working well.

**Comment by ClashLuke** [comment]
Okay, I'm very sorry for my very harsh response previously, I think I misunderstood something.
What I'm taking out of this discussion is, if we are able to implement an algorithm into the xmr-stak code without violating the licenses, causing harm for the rest of the code or just implementing a bugfilled, you will probably accept the pull request?

**Comment by Spudz76** [comment]
Yes please do, add your own mods for whatever coin, that's how open source works?
You just can't redistribute the modified code, or compiled binaries from such, you have to submit PR if you want to share with others.
Private use do whatever you want.

**Comment by psychocrypt** [comment]
He can dork xmr-stak and add his changes. The only requirement is that he
keeps the change puplic visible in his branch. A pull request is not
required
