### ISSUE TITLE
Keccak algo support?

### ISSUE THREAD

**Issue by tiagosiebler** [fireice-uk/xmr-stak#2048]
Can I mine a pool that needs the Keccak algorithm?

It's not in the list here:
https://github.com/fireice-uk/xmr-stak#supported-altcoins

But I did find this logic, so I'm not sure if I can put "keccak" as a currency in my pools.txt?

https://github.com/fireice-uk/xmr-stak/blob/master/xmrstak/backend/cpu/crypto/c_keccak.c

**Comment by stoksc** [comment]
That file is there because Keccak is used in the CryptoNote algos but it is part of a much larger process. I don't think xmr-stak supports _just_ Keccak coins that use Keccak like BTC uses SHA256. What were you trying to mine?

**Comment by tiagosiebler** [comment]
Was curious about the feasibility of mining SmartCash: https://eu-mine.smartcash.cc/getting_started

**Comment by stoksc** [comment]
Yeah, I think you'll want to look at [sgminer](https://github.com/sgminer-dev/sgminer) instead, since SmartCash's hashing algorithm is _just_ plain old Keccak. Keccak and XMR based algos are completely different even though XMR algos use Keccak. XMR algos just use it for scratchpad initialization. They also use all the other algos in that crypto folder you linked. This might help you put the picture together and its a pretty interesting read, too, to understand the asic/fpga resistance of XMR:
https://cryptonote.org/cns/cns008.txt
Maybe someone more experience with xmr-stak can correct me, though.

**Comment by tiagosiebler** [comment]
Definitely interesting, thanks!
