### ISSUE TITLE
Vega 56/64 Dual Thread - Should 2nd thread have lower Intensity

### ISSUE THREAD

**Issue by BKdilse** [fireice-uk/xmr-stak#2173]
Just wanting to understand why the 2nd thread on an AMD should have a lower Intensity to the 1st thread.

e.g.

1952/1952 Works well
2016/1920 Also works.

I've seen some posts with the 2nd thread lower.  What is the reason for this?

**Comment by Spudz76** [comment]
When they have identical intensity then the work farming collides (stacks up all at the same moment) more often.  Every time a thread finishes a cycle the main executor has to check its PoW and then farm it some more work.  Doing all this work at the same microsecond instead of spreading it out hurts performance (verifications are done on CPU).

The newer option `interleave` was added to fix this collision by adding random delays so the threads start and end at different times.

So, on older versions without `interleave` option, making the intensity different made the threads start and end skewed over time, which worked smoother.  But now with the collision avoidance it doesn't matter either way, in fact same intensity might be best.

**Comment by BKdilse** [comment]
Thanks for that explanation, makes sense.  As I'm on the latest version with interleave at default, I'll keep intensity the same.
