### ISSUE TITLE
Next hardfork update?

### ISSUE THREAD

**Issue by baboda52525** [fireice-uk/xmr-stak#2532]
boom

**Comment by psychocrypt** [comment]
I am currently preparing the last peaces. the code is since weeks in one of
my branches visible but I do not point directly to it because I like avoid
that users test a versin before there is a monro testnet pool available.
A few days ago there was no testnet pool available.
I will checkit again, if you know a testnet pool please report the access
data here.

I will try to have the first official version in two weeks. I am on a
business trip and can not prepare binaries.

This schedule will give you 1.5 month for testing.
