### ISSUE TITLE
xmr-stak git clone

### ISSUE THREAD

**Issue by neutral1030** [fireice-uk/xmr-stak#2583]
Hello,
I'm trying to compile xmr-stak-rx on Linux but can't compile with new miner. Below are my commands.

git clone https://github.com/fireice-uk/xmr-stak.git

mkdir xmr-stak/build

cd xmr-stak/build

cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF

make install

**Comment by psychocrypt** [comment]
please go into the directory xmr-stak and switch to the correct branch.

```
cd xmr-stak
git checkout xmr-stak-rx
cd build
cmake .. -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF
make 
```

The binary will be in the `bin` folder. If you call `make install` you must be root because by default the miner will be installed to `/usr/`

If you have compile errors please post the output (full, including the used commands)

**Comment by neutral1030** [comment]
Thanks for the quick reply!
