### ISSUE TITLE
How in Windows to compile with CUDA 7.5 ?

### ISSUE THREAD

**Issue by sergneo** [fireice-uk/xmr-stak#277]
Gives an error when compiling.
```
"C:\xmr-stak-2.0.0\build\install.vcxproj" (целевой объект по умолчанию) (1) ->
"C:\xmr-stak-2.0.0\build\ALL_BUILD.vcxproj" (целевой объект по умолчанию) (3) -
>
"C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj" (целевой объект по умолч
анию) (7) ->
(CustomBuild конечный объект) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\
VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" завершил
ась с кодом 1. [C:\xmr-stak-2.0.0\build\xmrstak_cuda_backend.vcxproj]

    Предупреждений: 28
    Ошибок: 1
```

**Comment by psychocrypt** [comment]
Please change you language next time to english.  

It could be that Visual Studio 2017 not supports CUDA 7.5. Please update to CUDA 8+ to compile the miner on windows.

**Comment by JerichoJones** [comment]
I think you'll need Visual Studio 2013 to use CUDA 7.5 if I recall correctly. This is something on my ToDo list that I have not gotten around to trying.

**Comment by sergneo** [comment]
I need a miner under the GPU architecture 2.1. 
cmake -DCUDA_ARCH=20 gives an error on top

WARNING: NVIDIA GPU 0: miner not compiled for the gpu architecture 21.
[2017-11-30 12:37:13] : WARNING: NVIDIA setup failed for GPU 0.

**Comment by psychocrypt** [comment]
I will build the next release with fermi support. I think this weekend.

Am 30.11.2017 12:06 Nachm. schrieb "sergneo" <notifications@github.com>:

I need a miner under the GPU architecture 2.1.
cmake -DCUDA_ARCH=20 gives an error on top

WARNING: NVIDIA GPU 0: miner not compiled for the gpu architecture 21.
[2017-11-30 12:37:13] : WARNING: NVIDIA setup failed for GPU 0.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/fireice-uk/xmr-stak/issues/277#issuecomment-348156863>,
or mute the thread
