### ISSUE TITLE
wrong network error count

### ISSUE THREAD

**Issue by psychocrypt** [fireice-uk/xmr-stak#30]
Network errors get counted twice after the first error.

After the first error each followed error is counted as two errors.
This is can be reproduced by disconnect the system from the network during the mining. After the first error is triggert plug the system in again and after the miner get a new job unplug the miner again. Than if the next share is found the miner is counting the error as two connection errors.

**Comment by fireice-uk** [comment]
This has been fixed on CPU with the commit 7a6842dbd9351f4b00f0afd6cf4033036f130249 I didn't port it to other miners since at that point we were pretty much decided on unifying the miner

**Comment by fireice-uk** [comment]
@psychocrypt can you do a step-by-step instruction to trigger the error? I broke it down like that:

1. disconnect the system from the network during the mining. 
2. After the first error is triggert plug the system in again 
3. after the miner get a new job unplug the miner again. 
4. if the next share is found the miner is counting the error as two connection errors.

Step 4 never occurs since the miner stops mining when it is offline

**Comment by psychocrypt** [comment]
Mhh I can't reproduce it anymore. I tested it twice but the count was always correct.

closed: issue can not be reproduced
