### ISSUE TITLE
"job not found" and "invalid nonce" on NiceHash

### ISSUE THREAD

**Issue by rpm604** [fireice-uk/xmr-stak#309]
I'm getting two very specific rejected shares right now.

Rig 1:

• 1724 / 1773 (97.2%)
• 41 job not found
• 8 invalid nonce

Rig 2:

• 1880 / 1935 (97.2%)
• 41 job not found
• 14 invalid nonce

5 Vegas across 2 rigs, using xmr-stak, in the actual NiceHash app.

Using XMR-stak directly to a Monero or Aeon pool gets either no or VERY few rejected shares (0.2%, usually network issue)

I can't find details about these specific rejected shares. I'd like to fix this as it's an awful hit to my earning.

**Comment by JerichoJones** [comment]
Nicehash is probably dead after the hack.

**Comment by rpm604** [comment]
@fireice-uk This issue is not resolved, and is still happening with the relaunch of NiceHash.

I understand that NiceHash isn't liked particularly much, but I'd rather the issue be open instead of closed?

**Comment by psychocrypt** [comment]
IMO the job not found is an issue on the pool side. There is no reason why
it should only happen if nicehash is activated.

**Comment by Frianik** [comment]
Its all about stak. Have 2 rigs with 6x64 and 4x56 vegas. all reference. at stak i got ~10% "No job found". After switching to cast xmr i got 0% bad shares and got 10% boost hashrate in monitoring. Fix it please. I really love stack - 6x64 rig gives me 12200h/s when cast give only 11800.

**Comment by toekyoe** [comment]
I have the same issue where 10-20% of the shares are rejected.  I don't have this issue when mining XMR directly.  @psychocrypt may be right that it is largely a NiceHash issue, but I really don't know the cause.  Maybe NiceHash is doing a terrible job of sending out new blocks to be solved?

**Comment by Mortalinho** [comment]
I got the same issue except it is round about 5 % job not found.

**Comment by 2001blader** [comment]
I'm having the same issue, at about 10%. I think it has to do with nicehash share difficulty being so high, compared to other pools.

**Comment by JerichoJones** [comment]
This is related to poor performance of nicehash proxies. Contact them and let them know the issue that you are having with their pool.

**Comment by toekyoe** [comment]
thanks @JerichoJones

**Comment by toekyoe** [comment]
To people who have this issue: please go to https://www.nicehash.com/support and submit a ticket so that this issue is elevated.

**Comment by Mortalinho** [comment]
The answer:

"Please try another version of program.
https://github.com/nicehash/NiceHashMinerLegacy/releases

The difficulty for mining Cryptonight is very high at the moment because a lot of miners are mining it and miners with better hardware get shares faster than you.

Kind regards,
NiceHash Team"

**Comment by nikl11** [comment]
FIX: I connected to a different nicehash server (brazil), and now my shares are 100% correct!!! Both EU and US gave me about 4% rejected shares.

**Comment by Mortalinho** [comment]
Not for me. Still the same amount of job not found and miner not compatible after switching to brazilian server.

**Comment by nikl11** [comment]
Yeah, I spoke too soon. I had a series with 80 perfect shares, followed by 5 invalid shares, followed by a standard 5% invalid shares. Damn! Why is this happening, 5% is sooo much. Is nicehash just giving their server an easier time and we are paying for it? 200k diffulty is quite a lot if you ask me, though it should not cause job not found errors. It seemes like once a block is found, servers just move on and they discard our work.

**Comment by prettycode** [comment]
I recently switched to nicehash after mining XMR directly and have gone from 99.X% "good results" with supportxmr.com to 92 - 94% with nicehash. Ugh, pretty frustrating. If cryptonight wasn't so profitable through nicehash because of SUMO and ETN, there's no way I'd put up with this.

**Comment by nikl11** [comment]
Yeah, exactly. BUT, since yesterday I tried a different mining software for my vega (c***_**r), and I have all results correct so far. I think it is xmr_stak's issue a little bit as well. @psychocrypt , I think you should look into this. I would prefer xmr_stak hands down, because I don't trust closed binaries, especially in the crypto world where one percent higher fee can literary make millions of dollars without any fear of any punishment, but 3-5% incorrect shares is just way too much to begin the whole spiral of fees with.

**Comment by psychocrypt** [comment]
We know that minergate produce a similar issue. Some miner sending all
there shares twice if the pool returned an error. This is not a standard
conform way because this can lead ro bans on a pool because you spam the
pool with wrong results.
Nicehash should fix there server or proxies. I thinks the proxys has to
much load which creates the wrong results.

**Comment by rpm604** [comment]
@nikl11 I don't trust that program's reporting. Check circusdad's mining guide for Vega to see the comparison.

@psychocrypt I appreciate all of your work. The miner is great, and the problem is pretty clearly on NiceHash's side, to me.
