### ISSUE TITLE
stak hung up for 5 hours. Pulling wattage but nothing sent to pool

### ISSUE THREAD

**Issue by gregv64** [fireice-uk/xmr-stak#415]
i restarted the miner, checked on it 30 mins before going to bed. woke up 6 hrs later, still pulling full wattage from the wall, however the last time stamp in the command lines was from 5 hours ago, checked the pool (minexmr) and i had no shares sent over there in the last 5 hours... any idea?
if it had no connection shouldn't the miner have terminated itself?

**Comment by miziel** [comment]
I had exact same thing with stak-nvidia before [https://github.com/fireice-uk/xmr-stak-nvidia/issues/139](#139 with stak-nvidia) - it might have something to do with switching to dev pool

**Comment by renownedd** [comment]
I had the same issues a few times. After turning down my OC and the values in the config files it seems to run more stable. Others are reporting this issue on reddit.

**Comment by gregv64** [comment]
miziel: yes it appears this is the problem. when i press H, i keep seeing the message thanks for donating witht he devpool:333 address in there all the time... Have I just been donating for those 5 hours??

**Comment by zr26060** [comment]
I had same issues , looks like I have been donating 50% today

**Comment by OGGrandma** [comment]
I would like to report this problem as well, seems to be an issue related to the switching. I also noticed lots of "Result Rejected by pool" when I came home to check. Went back to normal after restarting xmr. I'm worried why this is happening.

**Comment by renownedd** [comment]
I had an issue with it twice today where it stuck switching to dev pool was
offline for 2 hours because it happened when I was away from home.
Restarting the program seems to resolve until it happens again.

**Comment by psychocoderHPC** [comment]
we will check the code qgain if there is a bug vidiable.

**Comment by psychocrypt** [comment]
we will check the coresponding code again.

Am 10.12.2017 12:03 schrieb "renownedd" <notifications@github.com>:

> I had an issue with it twice today where it stuck switching to dev pool was
> offline for 2 hours because it happened when I was away from home.
> Restarting the program seems to resolve until it happens again.
>

**Comment by fireice-uk** [comment]
`if it had no connection shouldn't the miner have terminated itself?`

It will if you set giveup_limit

@miziel 
` it might have something to do with switching to dev pool`

That is actually very unlikely, at least in your case. The pool selection code is totally different between stak 1.x and 2.0

@gregv64  
` i keep seeing the message thanks for donating witht he devpool:333 address in there all the time... Have I just been donating for those 5 hours??`

Please press C to see which pool you are connected to. And no, a thank you message doesn't mean you are donating right now.

@zr26060 
`I had same issues , looks like I have been donating 50% today`

In that case reduce your donate-level.hpp from 50%.

@OGGrandma 

`I would like to report this problem as well, seems to be an issue related to the switching. I also noticed lots of "Result Rejected by pool" when I came home to check. Went back to normal after restarting xmr. I'm worried why this is happening.`

Can you post the log please?

@renownedd 

`I had an issue with it twice today where it stuck switching to dev pool was
offline for 2 hours because it happened when I was away from home`

Can you post the log please?

**Comment by renownedd** [comment]
@fireice-uk I think it got stuck switching because the last thing in the cli is thanks for donating. I had it freeze up on me today again. It did say thanks for donating but it was totally locked up, pulling full wattage and using the entire load. Burning up for no reason, no shares submitted to my pool for 13 hours! When you say post the log do you mean what is in the cli window?

**Comment by JerichoJones** [comment]
Edit your config file to enable logging...

/*
 * Output file
 *
 * output_file  - This option will log all output to a file.
 *
 */
"output_file" : "",

**Comment by renownedd** [comment]
What do I do with that?

**Comment by JerichoJones** [comment]
Edit the config.txt and enable logging. As shown below

/*

Output file
output_file - This option will log all output to a file.
*/
"output_file" : "mylog.txt",

Post the results here.

**Comment by fireice-uk** [comment]
@renownedd Changed the thank you message

`
PS This is just a thank you. 
It doesn't mean you are mining to our pool right now.
`
