### ISSUE TITLE
[Feature request] Temperature and fan speed display

### ISSUE THREAD

**Issue by bomb-on** [fireice-uk/xmr-stak#658]
It is possible to include something like that in some of the future versions? Something very simple, similar to what cast-xmr has (`[10:36:49] GPU3 | 59°C | Fan 3640 RPM | 2041.4 H/s`)...

Also, thanks for this brilliant program and all your efforts!!

**Comment by psychocrypt** [comment]
A I wrote in  #225 it is much more usefull to monitore the system with a monitoring tool like centreon, munim, ganglia, ...
If we add monitoring to the miner we get three new dependencies. Please check centreon it support windows and linux systems.

**Comment by bomb-on** [comment]
How the hell did I miss the issue you linked?? ^^

Yeah, if you have to include additional dependencies, might not be the best idea... More dependencies means just more troubles... Focus on important stuff, rather than decorations ;)

Thanks for suggestions, those apps seem perfect, will definitely try one out...

**Comment by psychocrypt** [comment]
Yes focussing on the miner and not colored output, monitoring and create a
"I can do everything a little bit but nothing good miner" is currently our
way we go.
That not means that we will not have such features in the far future but
currently we are still focusing our time to improve the core.

**Comment by holitics** [comment]
I would like to also add a request for some very basic GPU health stats (temperature, fan speed).
It does not have to be fancy, i.e. just a part of the JSON API string that is returned giving those numbers per GPU. Most other miners have that basic information included in their APIs. Monitoring software can then model directly to the miner API instead of having to use a 4th party tool to get additional statistics and having to install additional agents on each and every box.

**Comment by rodneymo** [comment]
@psychocrypt, the main shortcoming of your suggestion is the need to install/maintain yet another piece of software on every rig (the monitoring tool agent) so providing the fan, temp as part of the mining software API helps reducing the operational effort and rig resource usage
