### ISSUE TITLE
Stop UAC popup when use_slow_memory=always

### ISSUE THREAD

**Issue by huserbg** [fireice-uk/xmr-stak#680]
When mining only with GPU, large pages are irrelevant (the hashrate is exactly the same with and without them).
That's why I prefer to **not** run the miner as Administrator in Windows.
The miner still tries to allocate large pages and shows errors, so I put `"use_slow_memory" : "always"` in config.txt. Even then, it still shows UAC popup, so I have to run it with `--noUAC`.
It will be good to check config.txt first and skip UAC if `"use_slow_memory" : "always"` is found.

Another (even better) option will be to disable large pages automatically if the miner is run with `--noCPU` or it has been compiled with `-DCPU_ENABLE=OFF`.

**Comment by psychocrypt** [comment]
Thanks for your suggestion.
Even if you disable cpu mining the cpu is used to validate the hashes from
the gpu. It is also there usefull to have large page suppory, therefore we
can not disable it.
But you are right if slow mem is activated than we can skip the uac dialog.
We need to check if it is possible because we read the config file very
late in thw program flow.

**Comment by fireice-uk** [comment]
Marked for todo.
Elevate on as-needed basis:

- Windows 7  - when using fast mem
- Windows 10 - when setting up user permissions

**Comment by fireice-uk** [comment]
Implemented in #702
