### ISSUE TITLE
Not able to download xmr-stak-win64.zip. Failed - Virus detected. How to download?

### ISSUE THREAD

**Issue by prakki79** [fireice-uk/xmr-stak#693]
Not able to download xmr-stak-win64.zip. Failed - Virus detected. How to download? Help!!

https://github.com/fireice-uk/xmr-stak/releases

**Comment by psychocrypt** [comment]
You need to add a exeption to your av software or switxh to linux.

**Comment by prakki79** [comment]
thanks.
even the IE, FF, Chrome.. stops it from downloading. Any other options in windows?

**Comment by Nisthar** [comment]
@psychocrypt Does changing some code in source and rebuilding makes it bypass av detection?
I have used this method to make my python executables fud.

**Comment by nagalman** [comment]
The reason antivirus software recognizes this as a virus or malware is because Monero mining is actually used as malware in some cases. Websites are poping up that run a JavaScript Monero miner in the users browsers. As a result antivirus correctly identifies it as a virus. 

Like stated in a previous comment, you need to add a exception to your antivirus software. I have been able to download the file successfully with FireFox.

**Comment by fireice-uk** [comment]
@Nisthar It does, even just building it, however herders are a lazy bunch.

**Comment by Tech-CF** [comment]
Go to your Windows Defender security center. Enter your scan log. You'll find entries for Trojan:;Win32/Fuery.A!cl and HackTool:Win64/CoinMiner. Click them and select "allow on this computer".
