### ISSUE TITLE
Move all config to one file

### ISSUE THREAD

**Issue by fireice-uk** [fireice-uk/xmr-stak#73]
There is no point in having separate files for config. JSON values should be renamed and integrated as optional (kNullType) values.

`cpu_threads_conf` (no rename)
`gpu_threads_conf` -> `amd_threads_conf`
`platform_index` -> `opencl_platform_index`
`gpu_threads_conf` -> `nvida_threads_conf`

Autoconfig should build the config.txt by appending the relevant templates.

**Comment by fireice-uk** [comment]
@psychocrypt Let me know if you can pick up this one.

**Comment by psychocrypt** [comment]
There are a few reason to not join the config files:
  - If we merge all configs to one than it is hard to detect if we need to trigger the auto suggestion.
  - removing the file for a back-end will trigger the auto suggestion (the old way with editing the config was to error prone)
  - if an user has driver issues (mostly opencl) than the config file will created as soon as the issue is solved
  - Testing for us is currently very easy, I can keep the general config and can switch the system with a different setup and start my tests. If I need always edit configs by hand everything will be slower and error prone.

You said me in the past that the JSON writer is not able to create human readable files. Never the less most of my points above say that the normal user can not editing JSON files to remove maybe a backend configuration if he did something wrong. This means he will delete the full file with all configs and than begin to copy past maybe partly hand tuned configs into the new config file which fast results in errors and issues for us.

I know that JSON has a nice hierarchical format but I would prefer to keep back-end config independent.

**Comment by psychocrypt** [comment]
IMO also big miner with many systems has an advantage with the current separation, thy can have on general config and depending on the rig back-end configs. This makes the organisation much easier.

**Comment by fireice-uk** [comment]
Ok. I will drop this one, at least for now.
