### ISSUE TITLE
lots of 'AMD Invalid Result' 

### ISSUE THREAD

**Issue by the-babaji** [fireice-uk/xmr-stak#791]
ubuntu server 16.04

using sapphire radeons 570's 4gb

# Stability issue
  - overclocked
  - and undervolted

just one of my rigs (with 7 cards) is getting these errors, at least 18 in the last day, my other rig (also 7 cards) , similarly spec'd gets none of these errors ever. 

I reckon, it's an over cooked card, but that's just a guess. what does this error mean? Is this causing me wasted work, bad shares etc....?

Any way to narrow it down? I'd love to be able to find a way to identify the offending card(s) on this rig, Is there a log file I can check? or a command to monitor the cards? Anything?

Thanks

**Comment by borzaka** [comment]
I would say is it because the overclocks. Your valid shares submitted to the pool will be less (you are payed for your submitted valid shares). And your hashrate will be lower.

You can test each card one-by-one by commeting out the rest, and leaving only one card in the amd.txt and let it run for few hours, check results, and than switch to another card.

Or you can try other CryptoNight miner, to see is there any difference in valid results.

**Comment by the-babaji** [comment]
Thanks, i thought of pulling the cards or at least powering down the risers one by one until the errors went away. I guess remarking them out of the amd.txt file will also work. The down side with that is the down time for the card, i rather minimise the time it takes to identify the card.

I found this command:: 

> **sudodmidecode -t slot**

> Handle 0x0021, DMI type 9, 17 bytes
> System Slot Information
> 	Designation: PCIEX1_1
> 	Type: x1 PCI Express
> 	Current Usage: In Use
> 	Length: Short
> 	ID: 0
> 	Characteristics:
> 		3.3 V is provided
> 		PME signal is supported
> 	Bus Address: 0000:05:00.0
> 
> Handle 0x0022, DMI type 9, 17 bytes
> System Slot Information
> 	Designation: PCIEX16_1
> 	Type: x16 PCI Express
> 	Current Usage: In Use
> 	Length: Long
> 	ID: 1
> 	Characteristics:
> 		3.3 V is provided
> 		Opening is shared
> 		PME signal is supported
> 	Bus Address: 0000:01:00.0
> 
> Handle 0x0023, DMI type 9, 17 bytes
> System Slot Information
> 	Designation: PCIEX1_2
> 	Type: x1 PCI Express
> 	Current Usage: In Use
> 	Length: Short
> 	ID: 2
> 	Characteristics:
> 		3.3 V is provided
> 		Opening is shared
> 		PME signal is supported
> 	Bus Address: 0000:08:00.6
> 
> Handle 0x0024, DMI type 9, 17 bytes
> System Slot Information
> 	Designation: PCIEX1_3
> 	Type: x1 PCI Express
> 	Current Usage: In Use
> 	Length: Short
> 	ID: 3
> 	Characteristics:
> 		3.3 V is provided
> 		PME signal is supported
> 	Bus Address: 0000:06:00.1
> 
> Handle 0x0025, DMI type 9, 17 bytes
> System Slot Information
> 	Designation: PCIEX16_2
> 	Type: x16 PCI Express
> 	Current Usage: In Use
> 	Length: Long
> 	ID: 4
> 	Characteristics:
> 		3.3 V is provided
> 		Opening is shared
> 		PME signal is supported
> 	Bus Address: 0000:02:00.1
> 
> Handle 0x0026, DMI type 9, 17 bytes
> System Slot Information
> 	Designation: PCIEX1_4
> 	Type: x1 PCI Express
> 	Current Usage: In Use
> 	Length: Short
> 	ID: 5
> 	Characteristics:
> 		3.3 V is provided
> 		Opening is shared
> 		PME signal is supported
> 	Bus Address: 0000:09:00.7
> 
> Handle 0x0027, DMI type 9, 17 bytes
> System Slot Information
> 	Designation: PCIEX16_1
> 	Type: x16 PCI Express
> 	Current Usage: In Use
> 	Length: Long
> 	ID: 6
> 	Characteristics:
> 		3.3 V is provided
> 		PME signal is supported
> 	Bus Address: 0000:04:00.4



it gives lots of interesting output, including a bus address and also seems to tell you in what slot the card is located on the motherboard.

A while ago I had a crash that showed a lot of gibberish on the screen (error messages)  but in those messages repeated over and over was the bus address of the card. It allowed me to locate the card very quickly, pull it and  and lower the overclocking a little. Since then it has not been hard crashing like it was before.

Just wondering if there is anyway XMR-STAK could report back these errors to us and if possible a bus address for the card?

**Comment by bruslie** [comment]
are you using the same motherboards on your 2 rigs ?

**Comment by the-babaji** [comment]
yes same motherboard on both rigs

**Comment by borzaka** [comment]
If you are afraid of downtime, there is another way:
- lower the overclocks on card 1, and check the invalid results, if the invalid results are increasing, then lower the overclocks on card 2 and so on...

There is a possibility, that the invalid shares are coused by multiple cards. Reset all cards to stock settings, and overclock them one-by-one and check invalid results.
You need time to invalid results to appear after overclock changes.

**Comment by the-babaji** [comment]
Still I guess what I would like to know, is there a way to be notified by a report, a log file etc.... where these errors are being produced. Is there not an audit trail?

**Comment by borzaka** [comment]
I think that's a feature request to xmr-stak: the result report should indicate which GPU has invalid results.

**Comment by fireice-uk** [comment]
This has been implemented 5 days ago  (#754), it is currently on the unstable dev branch.

**Comment by mikeuding** [comment]
Just sharing some experiences with my **AMD Radeon RX 550 2GB** rig mining monero7

I ran into 100% **AMD Invalid Result** on every card when i undervolted my AMD cards with **OverdriveNTool** and setting the "strided_index" too high, at 16 to be precise, in the amd.txt config file. "strided_index" at 8 was ok. Only a little less undervolting and everything runs fine, also at strided_index: 16.

At first resetting the cards with the 'Reset All' button on [ONT](https://forums.guru3d.com/threads/overdriventool-tool-for-amd-gpus.416116/) did not work and i was still getting those invalid results. Turned out it had something to do with the AMD Settings. Like it took over the undervolted settings or whatever. Finally i uninstalled the driver with [DDU](http://www.guru3d.com/files-details/display-driver-uninstaller-download.html) and custom reinstalled the drivers (18.7.1) only. So no sound over hdmi and AMD settings etc.

Running it with **Windows 10 Pro**, [**Adrenalin Edition 18.7.1**](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-18-7-1), [**xmr-stak 2.4.5**](https://github.com/fireice-uk/xmr-stak/releases/tag/2.4.5)

Cards have custom bios [(with **oneclicktiming patch**)](https://www.xmrstak.com/2018/04/16/sapphire-rx-550-520-h-s-one-click-timing-patch/)

Maybe also useful:

_Small script to display AMD GPU ordering in xmr-stak vs OverdriveNTool._
https://gist.github.com/eriktorsner/ac2306b08de26484300649be1c8d15d6

---

GIGABYTE Radeon RX 550 D5 2G
Sapphire Pulse Radeon RX 550 2GD5

RX550, 1 x1 to 4 x1 multiplier, AsRock AB350M Pro4, Windows 10 Pro
