### ISSUE TITLE
Excuse the dumb question, but how do i get to the miner to open?

### ISSUE THREAD

**Issue by BigShadex** [fireice-uk/xmr-stak#880]
First time using XMR stak miner, normally there is a .exe file to open and i go from there, however this one doesn't seem to have one.. What am i doing wrong :(

**Comment by psychocrypt** [comment]
Maybe you downloaded the wrong zip file. Please download https://github.com/fireice-uk/xmr-stak/releases/download/v2.2.0/xmr-stak-win64.zip and check that you virus protection software is not removing the exe file. The most virus software detect xmr-stak as trojan and removes the exe file.

**Comment by BigShadex** [comment]
Yep ok! i found that .exe file last night after some hunting... However now i only get the option to mine Monero or Aeon.. How do i change that to ETN?

**Comment by anazhd** [comment]
Just choose monero.

**Comment by BigShadex** [comment]
Anazhd, but that means id be mining Monero... Not ETN?

**Comment by anazhd** [comment]
ETN is a Monero fork (don't want to prolong this because you will not understand). Since it's mostly using Monero codebase, then you are OKAY to use Monero algo to mine ETN. NO you will not be mining Monero as your selection of ETN pool actually means it directs YOUR hashes to solve ETN blocks.

too complicated, didn't read : use Monero option to mine ETN, as long as you put the right ETN address and ETN pool url.
