### ISSUE TITLE
Intel Xeon Phi Processors

### ISSUE THREAD

**Issue by jdmedeiros** [fireice-uk/xmr-stak#891]
First of all, apologies if this is the wrong place to place this, but I could not find another forum. Although I do not have a root account, or sudo rights, on this machine, I managed to compile xmr-stak with the help of EasyBuild and passing these options to cmake3 -DCMAKE_PREFIX_PATH=hwloc/1.11.5-GCC-5.4.0-2.26 -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DMICROHTTPD_ENABLE=OFF

To run xmr-stak I need to load the hwloc module and, of course, because I can not run it as root I get the **MEMORY ALLOC FAILED : mmap failed** and **hwloc: memory pinned** for every one, but it runs and mining Monero I am getting as high as 1.59 KH/s. However, this is nothing compared to what I would be able to get if I ran xmr-stak on the XEON Phi 7250 instead of running it on the Intel XEON E5-2643. Unfortunately I am not able to run it on the XEON Phi 7250 because I am not even allowed to ping 8.8.8.8 due to restrictions which results in 

> ping: socket: Operation not permitted

To take advantage of this monster, xmr-stak would need to offload the processor intensive routines to the XEON Phi 7250 and use the XEON E5-2643 as, shall we call it, the controller, which assigns tasks to the XEON Phi 7250, get the results and runs all communications with the mining pool (considering sockets are not allowed in the XEON Phi 7250.

I will try to modify the code and see if I can offload some small tasks to the XEON Phi 7250, but it would great if the developers could share some insights on how to go about it.

Here are the specs:

**Hardware**
Head node: 2x Intel XEON E5-2643 6-core processors, 64 GB memory, 22 TB storage)
Login node: 2x Intel XEON E5-2690 14-core processors, 64 GB memory
32x Compute nodes, 1x Intel XEON Phi 7250 (68-core processor), 16 GB high-speed cache, 96 GB DDR4 memory

`Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                24
On-line CPU(s) list:   0-23
Thread(s) per core:    2
Core(s) per socket:    6
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E5-2643 v3 @ 3.40GHz
Stepping:              2
CPU MHz:               3599.882
BogoMIPS:              6788.93
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0-5,12-17
NUMA node1 CPU(s):     6-11,18-23

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                272
On-line CPU(s) list:   0-271
Thread(s) per core:    4
Core(s) per socket:    68
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 133
Model name:            Intel(R) Xeon Phi(TM) CPU 7285 @ 1.30GHz
Stepping:              0
CPU MHz:               1000.000
BogoMIPS:              2593.93
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
NUMA node0 CPU(s):     0-271

Thanks!

**Comment by JerichoJones** [comment]
I have seen posts about the PHI on other forums. People are successfully mining on them. 
Try Bitcointalk or reddit/r/moneromining

**Comment by jdmedeiros** [comment]
Thanks, I figured it out! Managed to get constantly around 25 KH/s with peaks to 28 KH/s. This thing is a monster.

**Comment by ardatious** [comment]
@jdmedeiros 

could you please share how you did that? I'm only getting 372 hash/second per node on mine

did you use opencl, or something else?

**Comment by jdmedeiros** [comment]
opencl?  -DOpenCL_ENABLE=OFF right on the opening post. You sound like the guy who kicked me out of the platform trying to figure out how I did it. Are you on a XEON Phi platform? Post the specs like I did on the OP.

**Comment by ardatious** [comment]
I wasn't assuming that you had left all the parameters the same. 

If by getting kicked off a platform, you mean at a business or university someplace, it wasn't me. I'm in Tulsa Oklahoma, USA. I don't know where you are. I am running on my own servers, and I don't have access to anyone else's servers.

I am running on my own local machines. I have 90 dell r410s, 64 dell M610 and m620 blades, 1 supermicro 4 phi server, and 26 more 4n2u phi servers on order.

I  don't have much plugged in yet. Rewiring for more electric power.

Actually I'm the guy that sent a 250 amazon gift card to the facebook account of J. Daniel Medeiros with a message requesting help.  (true fact). 

as for platform I am running the supermico 4n2u phi 7210 server. I just used the basic cpu setup, except I put in 64 threads.  It is 4 nodes, each one is a 7210 processor on the motherboard. 64 cores i believe. 4 threads per core.  

If you want a phi node to test and run on, I'll have one free when my replacement fan arrives in a couple more days.

I'm not running xmr-stak on the phis right now because I have only two of four nodes running due to a crapped out fan.  I;m running lukminer on the two active nodes, each node generates 2750 khs on cryptonight using 254 threads. 

I'll take another swing at xmr-stak tomorrow and post things here.

**Comment by ardatious** [comment]
I did an lscpu on one node. each node is a server. There are 4 nodes in the box.

I am a newbie on linux, although I used both unix and xenix over 30 years ago. More recently I have taken college classes in c, java, and linux, but they don't teach much.  I've been programming since 1970 in various languages. I've done assembler, c, java, and visual basic programming on intel platforms starting in the 1980s.  Also some php and xcode.

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                256
On-line CPU(s) list:   0-255
Thread(s) per core:    4
Core(s) per socket:    64
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 87
Model name:            Intel(R) Xeon Phi(TM) CPU 7230 @ 1.30GHz
Stepping:              1
CPU MHz:               1469.017
CPU max MHz:           1500.0000
CPU min MHz:           1000.0000
BogoMIPS:              2599.76
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
NUMA node0 CPU(s):     0-255

**Comment by jdmedeiros** [comment]
I signed up [for one of this](https://software.intel.com/en-us/xeon-phi/x200-processor/remote-access) (the red one), read the trial terms very carefully and absolutely did not violate their terms in any way, shape or form for the simple reason they did not have any significant terms at the time. It hadn't occurred to them that someone would try mining. Well, I did. Now they have specific terms and prohibit any kind of mining. 

The first huge mountain I had to overcome was compiling xmr-stak directly on the Xeon Phi processor; it was a monster. They gave me shell access to the login node, which was an Intel XEON E5-2690, and they were expecting me to submit jobs using PBS commands like qsub, and their PBS management system would decide where to run the job with the limitations for time, cpus, memory, etc., that they had setup. How the heck was I going to qsub a compile of xmr-stack? Not doable. I did not want to compile xmr-stak on the login, or the head nodes, because I knew it would not run properly on the 7250, if at all, so I had to get into the 7250 itself and compile it there. 

The way I got into the 7250 directly, from my perspective, it's a design flaw on the part of Intel, which interestingly enough they changed and when I got a second trial (now with the green team which was running an update version), and this time I acknowledge I was violating the terms of trial, but the technical challenge overcame everything else, I was shocked I could no longer get into the 7250 directly. That shock only lasted a few hours; they (I imagine Intel) did not eliminate the problem completely; they only reduced the "window of opportunity" to get in there. Once I figured that out it was easy; I had it all outlined, so I was up and running in no time at all, hitting 20+KHz, and eventually got kicked out. I actually volunteered to tell them (the green team) how I did it; they never answered; still have the emails.

Now that I was in, how the heck was I going to compile xmr-stak that needs all kinds of packages if I was a simple regular user? Enter EasyBuild; one of the most awesome tools I ever saw and a system administrator's worst nightmare. Once I compiled it, I basically spawned it to every core available. The highest it got was about 28 KH/s and in a very short time I had .75 XMR, but keep in mind hwloc was off. Imagine if was on? But for that I would need root access. I would say compiling directly on the 7250 was crucial. I sure would like to find out how high it would have gotten with hwloc on.

I am not going to detail here how I did it. It could be a flaw on the part of Intel or on the way these companies installed and configure the OS. Either way, I will not make that information public. I strongly believe it's a flaw on the part of Intel. When I think about it, I can't even imagine how I came up with that idea, but I did. By the way @ardatious I was just kidding about you being the guy that kicked me out and I never got any message from you on Facebook, at least that I am aware of, but I hardly ever go there. I will be happy to help you out and compile xmr-stak for you remotely, although my time is very scarce and I have to wear many hats. Send me an email; I am sure you can figure it out.

This was never about the mining or making money. It was about the challenge. I actually suggested to one of the companies on the link to run xmr-stack full throttle for a while to see how far it could get. I thought it would be tremendous publicity for them, for xmr-stak and for Intel who is trying to position itself as a viable alternative to GPUs. They never answered, probably didn't get it. 

The very first computer I worked on professionally was an IBM System 34. It had less computing power than a two-bit watch of today and was more expensive than a Corvette. How could I resist 32x Compute nodes, 1x Intel XEON Phi 7250 (68-core processor), 16 GB high-speed cache, 96 GB DDR4 memory? 

Never in a million years!

**Comment by psychocrypt** [comment]
@ardatious if you can give me an ssh login to a phi I can help you. It will
take some time because I have limited time. One riquirement is a new intel
compiler must be installed. If you do this job I can install xmr-stak and
fix it if we have intel issues.

If you are interested please contact me via pm on reddit (psychocrypt) and
I provide you with my ssh key for login.

**Comment by jdmedeiros** [comment]
@psychocrypt  

>  One riquirement is a new intel compiler must be installed. 

I did not install or use the Intel compiler, which by the way was already built in. To use it I would have to do:
`module load intel/17.0.1.132`
`module swap intel gnu/5.4.0`
but that would only make sense if I modified the source code of xmr-stak to take advantage of the parallel processing capabilities of the platform, which is exactly what you want to do (take advantage of the parallel processing capabilities of the platform), but it's much easier to compile the source code as is with gnu and load multiple processes in each cpu. The end result is the same; I do manually what the Intel compiler would do for me at the cost of re-writing the source code.

**Comment by psychocrypt** [comment]
To use all features of the phi you must compile with intel. GNU has no
native support for phi.

**Comment by jdmedeiros** [comment]
Agree... but you must rewrite the source code.

**Comment by psychocrypt** [comment]
why? If xmr-stak is not compiling with the intel compiler we need only to
fix it. I never tried the intel compiler but I can do it . I assume
everything will work but I am not sure.

**Comment by jdmedeiros** [comment]
Download and read ["Best Practice Guide Intel Xeon Phi v2.0"](https://www.google.com/search?ei=O0zSWpG4IoiSsgGhy5awAw&q=%22Best+Practice+Guide+Intel+Xeon+Phi+v2.0%22&oq=%22Best+Practice+Guide+Intel+Xeon+Phi+v2.0%22&gs_l=psy-ab.3...4303.4303.0.4442.1.1.0.0.0.0.90.90.1.1.0....0...1.1.64.psy-ab..0.0.0....0.KjwjS-OGGVE) and then come back here and tell us what you think. I am sure you will agree with me.

**Comment by flash25296** [comment]
I am curious if this was ever figured out. I have an Asrock 4 Blade server with the Phi 7210's and I tried to compile XMR-STAK on the device running Ubuntu 16.04 and 18.04 and the miner software can not adequately handle the Xeon Phi processor. It is greatly reduced in performance. I like using XMR-STAK because of the development and versatality of the miner software but for now I have to use the LukMIner software and have a restricted set of Algos to choose from.

**Comment by jdmedeiros** [comment]
"...the miner software can not adequately handle the Xeon Phi processor". What do you mean? What rates are you getting with your compile version and with LukMiner?

**Comment by flash25296** [comment]
With the Lukminer stick on the Xeon Phi 7210 mining Monero we get around
2100 KH/s using XMR-STAK we get 513 h/s on XMRIG we get 415 H/s

We have large page enabled and we have tested on Ubuntu 18.04 and 16.04.

I am not sure what the guy who builds the Luk Miner Stick is doing but he
is clearly doing more with the PHI 7210s then these other mining apps.

**Comment by psychocrypt** [comment]
I can not look into this issue because I have no xeon phi. Also since intel
stopped to produce phi's it is not useful to invest time,sry

**Comment by flash25296** [comment]
Well there are a lot of 2U4N-F_X200 servers out there. I can get you an SSH
access into the machine if you are interested. I figure its the least I
could do.

Let me know
Michael

**Comment by psychocrypt** [comment]
If I should have a look into it drop me a message on reddir (name
psychocrypt) with the access information.
Please also all software which is required to  compile stak.
In which coin are you interested?

**Comment by jdmedeiros** [comment]
@psychocrypt please post your progress and keep me in the loop. I worked hard at this and luk-miner was on average 35% faster. I just dig up some specs which I am posting here for comparison. Something I remember as that upon starting up luk-miner was already up there whereas xmr-stak would take some time getting up up there.

 I changed CMakeLists.txt to include -O3 -xMIC-AVX512 and the make commands depending if the compiler was Inter 7 or 6 were:

cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME//INTEL/bin/xmr-stak-7 -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DCMAKE_CXX_COMPILER=icpc -DCMAKE_C_COMPILER=icc -DCMAKE_C_COMPILER_ID=Intel -DCMAKE_CXX_COMPILER_ID=Intel -DXMR-STAK_COMPILE=native -DMICROHTTPD_ENABLE=OFF -DOpenSSL_ENABLE=OFF -DCMAKE_BUILD_TYPE=Release ..

Intel 6:
make -DCMAKE_INSTALL_PREFIX:PATH=$HOME//INTEL/bin/xmr-stak-6 -DCUDA_ENABLE=OFF -DOpenCL_ENABLE=OFF -DCMAKE_CXX_COMPILER=icpc -DCMAKE_C_COMPILER=icc -DCMAKE_C_COMPILER_ID=Intel -DCMAKE_CXX_COMPILER_ID=Intel ..

The Intel compiler was slightly faster, but not significantly. Also, at the time, CentOS 7.3 and 7.2 and were the best OSs for the Xeon Phi https://software.intel.com/en-us/articles/xeon-phi-software but I never had an opportunity to try those OSs as I was experimenting remotely. 

![mining](https://user-images.githubusercontent.com/3796667/57980030-09461300-7a15-11e9-9e9c-a1706e38c551.png)

The best I got was about 4K, but it was not sustainable.
![xmp](https://user-images.githubusercontent.com/3796667/57980052-6c37aa00-7a15-11e9-856c-54537bbfa6f2.png)

Good luck!
